## Import Core Utilities functions

In [1]:
import warnings
warnings.filterwarnings("always")

from omicstl.simulation_utils.data_generation import response_function, generate_synth_data

## Load Data

In [2]:
import pandas as pd
import numpy as np

source_real_data_path = "data/source_data_real.csv"
target_real_data_path = "data/target_data_real.csv"

source_real_data = pd.read_csv(source_real_data_path, index_col=0)
target_real_data = pd.read_csv(target_real_data_path, index_col=0)

# Non-trivial continuous response function
response_fn = response_function("tanh(df[, 2]) + df[, 1] * df[, ncol(df)] ^ 2")

num_features = 100
num_samples_source = 100
num_samples_target = 50
samples_target_test = 25
samples_target_ensemble = 5

## Generate Linked Synthetic Datasets

In [3]:
# Continuous response

source_synth_data_cont, source_lc_info_cont, _ = generate_synth_data(
    data = source_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_source, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 # signal to noise ratio
)

target_synth_data_cont, _, _ = generate_synth_data(
    data = target_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_target + samples_target_test + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    prior_lc_info = source_lc_info_cont, # crucial to include else the source and target datasets aren't linked!
    snr = 1 # signal to noise ratio
)

display(source_synth_data_cont)
display(target_synth_data_cont)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,1.443538,0.589370,1.983488,2.996196,-0.554770,4.496169,-2.048098,4.573517,4.141948,4.659339,...,0.367196,0.445409,7.989305,6.557759,0.165861,1.168698,3.526412,3.434850,3.042302,-0.658559
1,1.631275,0.611849,1.918285,3.551464,-0.237760,3.970900,-1.744996,5.086129,4.111515,4.091370,...,0.407679,0.483109,8.049073,7.234136,0.120196,1.008032,4.047481,2.815058,3.411409,-0.970519
2,1.644228,0.509794,2.231702,3.765872,-0.956056,4.277639,-1.566257,4.985249,4.116960,4.271126,...,0.351109,0.401295,7.439326,6.905625,0.260790,1.013039,4.016236,3.074330,3.173546,-0.935049
3,0.582633,0.156010,0.647287,3.437727,-0.079878,4.439854,-2.089507,5.184383,3.998751,4.036167,...,0.318653,0.563949,8.183482,6.605963,-0.087493,1.167540,3.928379,3.047069,3.461859,-0.740999
4,1.436650,0.740364,2.211697,3.694348,0.044385,4.551903,-2.245445,4.836321,4.207446,4.154586,...,0.254579,0.500658,7.617232,6.800445,0.269721,1.223226,3.650267,2.776540,3.042302,-0.560634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.357928,0.883726,2.222434,2.794856,-0.312530,4.470488,-2.186053,5.042369,4.104947,4.240400,...,0.459062,0.563514,8.389921,6.236195,0.130420,0.907465,3.783304,3.112518,3.137995,-0.650133
96,1.265690,0.586275,2.198309,4.050321,-0.448881,4.257333,-1.365100,5.525735,3.837529,4.391789,...,0.219812,0.366624,8.369445,8.196204,0.160537,0.673499,3.779767,3.238269,4.069973,-0.511150
97,1.031847,0.058731,1.846210,3.042805,0.361526,4.619918,-1.520715,5.028478,3.821911,4.353849,...,-0.008122,0.394393,8.479281,7.722021,0.022690,1.131052,3.891375,2.808008,2.826529,-0.529751
98,1.529121,0.920922,1.120067,4.405622,-0.181510,4.556568,-1.827459,4.857745,3.893040,4.045761,...,0.493945,0.517122,8.348292,6.112088,0.273232,1.243684,3.570612,3.034458,3.695930,-0.825067
99,0.726144,0.762140,1.193297,3.530094,0.534424,4.267508,-1.791661,5.036631,3.972988,4.034904,...,0.443203,0.519697,8.502013,6.094283,0.192081,1.541221,4.081365,3.043697,3.303937,-0.706253

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,1.196630,0.496863,0.893903,3.667890,-0.025503,4.479654,-2.078406,4.876863,3.892328,4.676992,...,0.321255,0.454059,7.668439,7.772524,0.401080,1.190485,3.729853,2.707271,3.517486,-0.790799
1,1.194465,0.942130,1.190324,3.760448,0.094234,4.494671,-2.527750,4.451323,4.073032,3.997389,...,0.412883,0.422301,8.352741,6.823865,-0.095307,0.603919,3.696065,2.627055,3.529337,-0.410102
2,1.313259,0.576227,1.729690,3.483348,0.195682,4.210093,-1.497071,5.364139,3.960021,3.625390,...,0.122031,0.473001,8.461067,6.719611,0.225310,0.783630,4.096231,3.070661,3.153150,-0.859705
3,0.318715,-0.248177,1.084270,3.534676,0.429195,4.229483,-2.856093,4.998878,4.439467,3.864104,...,0.238774,0.454515,8.081329,7.202979,0.202775,1.095855,3.694321,3.510998,3.951333,-0.489137
4,1.227875,0.885270,1.266513,3.440139,-0.693982,4.135140,-1.048438,4.624136,3.999984,4.042575,...,0.084498,0.375252,7.728537,7.439578,0.141225,1.108690,3.934802,2.724861,3.531063,-0.577467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,1.284795,0.534947,2.470212,2.780449,-0.242202,4.635727,-2.005678,4.745673,4.168260,3.931118,...,0.388167,0.289294,8.444181,7.338210,0.172565,0.968576,3.993253,2.480624,4.088853,-0.827388
76,1.156234,0.279680,1.567083,3.621736,-0.890655,4.399405,-1.924618,4.765952,4.050981,4.424728,...,0.501184,0.612448,8.300250,8.154845,0.248014,1.078342,3.764108,2.850612,3.775272,-0.583132
77,1.529332,0.691696,1.638152,4.419714,0.120346,4.559314,-1.550746,4.771949,4.038930,3.923366,...,0.400786,0.272723,8.116208,7.312797,0.418771,1.257374,3.688337,2.472015,3.219959,-0.982941
78,1.474049,0.375221,1.818138,4.039631,0.103157,4.180431,-1.205213,4.722321,4.346224,4.317914,...,0.447257,0.392237,8.148898,7.623459,0.056153,1.075055,4.076749,3.015569,3.171410,-0.908475
79,1.253411,0.798628,2.235413,4.134228,-0.361322,4.149476,-2.004353,4.370233,4.423265,3.968095,...,0.094128,0.728390,8.340315,7.304449,0.347452,1.265566,4.003275,2.441924,3.322703,-0.656349

In [4]:
# Categorical response

source_synth_data_cat, source_lc_info_cat, _ = generate_synth_data(
    data = source_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_source + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    snr = 1, # signal to noise ratio
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

target_synth_data_cat, source_lc_info_cat, _ = generate_synth_data(
    data = target_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_target + samples_target_test + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 ,# signal to noise ratio
    prior_lc_info = source_lc_info_cat, # crucial to include else the source and target datasets aren't linked!
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

display(source_synth_data_cat)
display(target_synth_data_cat)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2.0,1.633587,0.724487,2.200324,-3.155215,-0.685482,0.278368,-1.151018,2.643381,3.529112,...,-1.344813,2.495672,0.186014,-1.087530,5.402589,-0.987140,2.686189,0.872104,-2.091750,-1.681481
1,3.0,1.879740,-0.190678,2.029219,-2.525152,-0.376699,0.458943,-1.442583,2.495748,3.658216,...,0.341776,1.987891,0.269912,-1.301663,4.684500,-0.980915,2.620241,-1.272310,-2.109084,-2.323157
2,3.0,1.871479,0.116167,1.852440,-2.865540,-0.597327,0.356310,-1.073322,2.587016,3.213658,...,1.101370,2.216324,0.347402,-0.630844,5.180305,-0.940925,2.142859,-0.128372,-2.289712,-2.171333
3,3.0,1.804296,0.564889,2.116092,-2.753530,-0.581191,0.965134,-1.548264,2.542412,3.611598,...,0.997871,2.166255,0.166201,-1.156944,4.721686,-0.970271,2.951272,-0.115046,-2.363075,-2.332624
4,1.0,1.753570,-0.390474,2.004941,-3.006513,-0.463152,0.741447,-0.996357,2.662096,3.743325,...,0.989446,2.438779,-0.028855,-1.190591,3.648381,-0.957171,2.935231,-0.837665,-2.572279,-1.753441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1.0,1.493399,-1.286366,2.180994,-2.794641,-0.518074,0.570271,-1.349549,2.429299,3.220166,...,-0.818521,2.451416,0.561467,-1.051045,5.731727,-0.950577,3.049027,-0.651621,-2.020382,-1.793567
101,1.0,1.853346,-0.847660,2.162192,-2.183244,-0.566748,0.831318,-1.362028,2.588418,3.580942,...,-0.101697,2.386903,-0.153740,-1.448605,4.272557,-1.107263,2.613351,-1.706302,-2.355149,-1.307574
102,1.0,1.937132,0.236331,2.148268,-2.488270,-0.428190,1.147100,-1.086616,2.691359,3.322599,...,-0.122475,2.739791,0.082001,-1.480864,5.873152,-0.979133,2.596650,-1.983193,-2.302872,-1.423733
103,1.0,1.643556,-0.959420,2.104094,-2.593146,-0.600169,1.022463,-1.105295,2.543349,3.414000,...,-0.318840,2.052134,-0.268990,-1.177454,4.346519,-0.956129,2.662385,-1.901102,-1.929536,-1.313531
104,1.0,1.684929,0.068160,2.107658,-2.507907,-0.532652,1.051104,-1.250411,2.489383,3.314888,...,0.257942,1.987626,-0.006314,-1.365367,4.790715,-0.972910,2.254520,-1.979088,-2.515249,-1.367805

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,3.0,2.053270,0.173531,2.128996,-2.753202,-0.327629,0.314818,-1.589560,2.600846,3.616749,...,0.755386,2.443228,0.305509,-1.505720,5.517377,-0.720506,2.522303,-2.711548,-2.500283,-2.679492
1,2.0,1.632452,0.510845,1.955767,-2.959171,-0.708348,0.529904,-1.477076,2.531814,3.372214,...,-1.289991,1.805820,0.030592,-1.116488,5.526046,-1.150046,2.989049,-1.010813,-2.285863,-1.735011
2,3.0,1.874809,-0.307597,2.050348,-2.335259,-0.534986,0.759694,-1.462699,2.490046,3.534952,...,0.159134,2.798794,0.139621,-1.316049,4.909905,-0.666629,2.588577,0.088475,-2.481844,-2.517725
3,3.0,2.055948,-0.039039,1.826668,-2.630403,-0.638002,0.664687,-0.757260,2.369401,3.547932,...,-1.557832,2.384457,0.288551,-1.150473,5.312439,-0.788347,2.741491,-0.362241,-2.403488,-2.006749
4,1.0,1.993814,0.626228,2.123430,-2.568481,-0.670118,0.824960,-1.366554,2.413033,3.727258,...,-0.553639,2.447007,0.261426,-1.733082,6.362278,-0.951700,2.869695,0.627546,-2.230731,-1.442407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2.0,1.709061,-0.116455,2.036383,-2.597020,-0.907886,1.038571,-1.326351,2.699232,3.346574,...,0.416196,2.138269,0.317000,-1.431819,5.351776,-0.871853,2.306323,-0.127611,-2.273822,-2.037293
76,3.0,1.924288,-0.588345,1.924117,-2.668794,-0.883919,0.861714,-1.248688,2.542697,3.353333,...,-1.162991,2.277523,0.128654,-1.593110,4.561308,-1.063216,2.701439,-1.160671,-2.339794,-2.290268
77,1.0,1.742533,0.454757,1.896593,-2.945253,-0.559005,-0.043019,-1.089511,2.342422,3.456428,...,-0.203662,2.077902,0.469032,-1.649820,5.165113,-1.112130,2.472960,-0.623667,-2.633995,-1.530874
78,3.0,1.757113,-0.066469,2.199332,-2.381653,-0.945429,0.230355,-1.862197,2.310520,3.475208,...,-1.706191,2.278381,0.462650,-1.017330,3.822980,-1.289053,2.385955,-1.525282,-2.259702,-1.834159
79,2.0,1.767550,0.266439,2.002653,-2.824913,-0.253299,0.653584,-1.282841,2.412166,3.395280,...,0.035107,2.618756,-0.050118,-0.839769,5.676709,-1.013659,3.374325,-1.333573,-2.479321,-2.037251

## Standardized Response Column Naming

In [5]:
# Set response column name

source_synth_data_cont.rename(columns={source_synth_data_cont.columns[0]: 'response'}, inplace=True)
target_synth_data_cont.rename(columns={target_synth_data_cont.columns[0]: 'response'}, inplace=True)
display(source_synth_data_cont)
display(target_synth_data_cont)

source_synth_data_cat.rename(columns={source_synth_data_cat.columns[0]: 'response'}, inplace=True)
target_synth_data_cat.rename(columns={target_synth_data_cat.columns[0]: 'response'}, inplace=True)
source_synth_data_cat = source_synth_data_cat.astype({"response": np.int64})
target_synth_data_cat = target_synth_data_cat.astype({"response": np.int64})
display(source_synth_data_cat)
display(target_synth_data_cat)

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,1.443538,0.589370,1.983488,2.996196,-0.554770,4.496169,-2.048098,4.573517,4.141948,4.659339,...,0.367196,0.445409,7.989305,6.557759,0.165861,1.168698,3.526412,3.434850,3.042302,-0.658559
1,1.631275,0.611849,1.918285,3.551464,-0.237760,3.970900,-1.744996,5.086129,4.111515,4.091370,...,0.407679,0.483109,8.049073,7.234136,0.120196,1.008032,4.047481,2.815058,3.411409,-0.970519
2,1.644228,0.509794,2.231702,3.765872,-0.956056,4.277639,-1.566257,4.985249,4.116960,4.271126,...,0.351109,0.401295,7.439326,6.905625,0.260790,1.013039,4.016236,3.074330,3.173546,-0.935049
3,0.582633,0.156010,0.647287,3.437727,-0.079878,4.439854,-2.089507,5.184383,3.998751,4.036167,...,0.318653,0.563949,8.183482,6.605963,-0.087493,1.167540,3.928379,3.047069,3.461859,-0.740999
4,1.436650,0.740364,2.211697,3.694348,0.044385,4.551903,-2.245445,4.836321,4.207446,4.154586,...,0.254579,0.500658,7.617232,6.800445,0.269721,1.223226,3.650267,2.776540,3.042302,-0.560634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.357928,0.883726,2.222434,2.794856,-0.312530,4.470488,-2.186053,5.042369,4.104947,4.240400,...,0.459062,0.563514,8.389921,6.236195,0.130420,0.907465,3.783304,3.112518,3.137995,-0.650133
96,1.265690,0.586275,2.198309,4.050321,-0.448881,4.257333,-1.365100,5.525735,3.837529,4.391789,...,0.219812,0.366624,8.369445,8.196204,0.160537,0.673499,3.779767,3.238269,4.069973,-0.511150
97,1.031847,0.058731,1.846210,3.042805,0.361526,4.619918,-1.520715,5.028478,3.821911,4.353849,...,-0.008122,0.394393,8.479281,7.722021,0.022690,1.131052,3.891375,2.808008,2.826529,-0.529751
98,1.529121,0.920922,1.120067,4.405622,-0.181510,4.556568,-1.827459,4.857745,3.893040,4.045761,...,0.493945,0.517122,8.348292,6.112088,0.273232,1.243684,3.570612,3.034458,3.695930,-0.825067
99,0.726144,0.762140,1.193297,3.530094,0.534424,4.267508,-1.791661,5.036631,3.972988,4.034904,...,0.443203,0.519697,8.502013,6.094283,0.192081,1.541221,4.081365,3.043697,3.303937,-0.706253

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,1.196630,0.496863,0.893903,3.667890,-0.025503,4.479654,-2.078406,4.876863,3.892328,4.676992,...,0.321255,0.454059,7.668439,7.772524,0.401080,1.190485,3.729853,2.707271,3.517486,-0.790799
1,1.194465,0.942130,1.190324,3.760448,0.094234,4.494671,-2.527750,4.451323,4.073032,3.997389,...,0.412883,0.422301,8.352741,6.823865,-0.095307,0.603919,3.696065,2.627055,3.529337,-0.410102
2,1.313259,0.576227,1.729690,3.483348,0.195682,4.210093,-1.497071,5.364139,3.960021,3.625390,...,0.122031,0.473001,8.461067,6.719611,0.225310,0.783630,4.096231,3.070661,3.153150,-0.859705
3,0.318715,-0.248177,1.084270,3.534676,0.429195,4.229483,-2.856093,4.998878,4.439467,3.864104,...,0.238774,0.454515,8.081329,7.202979,0.202775,1.095855,3.694321,3.510998,3.951333,-0.489137
4,1.227875,0.885270,1.266513,3.440139,-0.693982,4.135140,-1.048438,4.624136,3.999984,4.042575,...,0.084498,0.375252,7.728537,7.439578,0.141225,1.108690,3.934802,2.724861,3.531063,-0.577467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,1.284795,0.534947,2.470212,2.780449,-0.242202,4.635727,-2.005678,4.745673,4.168260,3.931118,...,0.388167,0.289294,8.444181,7.338210,0.172565,0.968576,3.993253,2.480624,4.088853,-0.827388
76,1.156234,0.279680,1.567083,3.621736,-0.890655,4.399405,-1.924618,4.765952,4.050981,4.424728,...,0.501184,0.612448,8.300250,8.154845,0.248014,1.078342,3.764108,2.850612,3.775272,-0.583132
77,1.529332,0.691696,1.638152,4.419714,0.120346,4.559314,-1.550746,4.771949,4.038930,3.923366,...,0.400786,0.272723,8.116208,7.312797,0.418771,1.257374,3.688337,2.472015,3.219959,-0.982941
78,1.474049,0.375221,1.818138,4.039631,0.103157,4.180431,-1.205213,4.722321,4.346224,4.317914,...,0.447257,0.392237,8.148898,7.623459,0.056153,1.075055,4.076749,3.015569,3.171410,-0.908475
79,1.253411,0.798628,2.235413,4.134228,-0.361322,4.149476,-2.004353,4.370233,4.423265,3.968095,...,0.094128,0.728390,8.340315,7.304449,0.347452,1.265566,4.003275,2.441924,3.322703,-0.656349

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2,1.633587,0.724487,2.200324,-3.155215,-0.685482,0.278368,-1.151018,2.643381,3.529112,...,-1.344813,2.495672,0.186014,-1.087530,5.402589,-0.987140,2.686189,0.872104,-2.091750,-1.681481
1,3,1.879740,-0.190678,2.029219,-2.525152,-0.376699,0.458943,-1.442583,2.495748,3.658216,...,0.341776,1.987891,0.269912,-1.301663,4.684500,-0.980915,2.620241,-1.272310,-2.109084,-2.323157
2,3,1.871479,0.116167,1.852440,-2.865540,-0.597327,0.356310,-1.073322,2.587016,3.213658,...,1.101370,2.216324,0.347402,-0.630844,5.180305,-0.940925,2.142859,-0.128372,-2.289712,-2.171333
3,3,1.804296,0.564889,2.116092,-2.753530,-0.581191,0.965134,-1.548264,2.542412,3.611598,...,0.997871,2.166255,0.166201,-1.156944,4.721686,-0.970271,2.951272,-0.115046,-2.363075,-2.332624
4,1,1.753570,-0.390474,2.004941,-3.006513,-0.463152,0.741447,-0.996357,2.662096,3.743325,...,0.989446,2.438779,-0.028855,-1.190591,3.648381,-0.957171,2.935231,-0.837665,-2.572279,-1.753441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1,1.493399,-1.286366,2.180994,-2.794641,-0.518074,0.570271,-1.349549,2.429299,3.220166,...,-0.818521,2.451416,0.561467,-1.051045,5.731727,-0.950577,3.049027,-0.651621,-2.020382,-1.793567
101,1,1.853346,-0.847660,2.162192,-2.183244,-0.566748,0.831318,-1.362028,2.588418,3.580942,...,-0.101697,2.386903,-0.153740,-1.448605,4.272557,-1.107263,2.613351,-1.706302,-2.355149,-1.307574
102,1,1.937132,0.236331,2.148268,-2.488270,-0.428190,1.147100,-1.086616,2.691359,3.322599,...,-0.122475,2.739791,0.082001,-1.480864,5.873152,-0.979133,2.596650,-1.983193,-2.302872,-1.423733
103,1,1.643556,-0.959420,2.104094,-2.593146,-0.600169,1.022463,-1.105295,2.543349,3.414000,...,-0.318840,2.052134,-0.268990,-1.177454,4.346519,-0.956129,2.662385,-1.901102,-1.929536,-1.313531
104,1,1.684929,0.068160,2.107658,-2.507907,-0.532652,1.051104,-1.250411,2.489383,3.314888,...,0.257942,1.987626,-0.006314,-1.365367,4.790715,-0.972910,2.254520,-1.979088,-2.515249,-1.367805

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,3,2.053270,0.173531,2.128996,-2.753202,-0.327629,0.314818,-1.589560,2.600846,3.616749,...,0.755386,2.443228,0.305509,-1.505720,5.517377,-0.720506,2.522303,-2.711548,-2.500283,-2.679492
1,2,1.632452,0.510845,1.955767,-2.959171,-0.708348,0.529904,-1.477076,2.531814,3.372214,...,-1.289991,1.805820,0.030592,-1.116488,5.526046,-1.150046,2.989049,-1.010813,-2.285863,-1.735011
2,3,1.874809,-0.307597,2.050348,-2.335259,-0.534986,0.759694,-1.462699,2.490046,3.534952,...,0.159134,2.798794,0.139621,-1.316049,4.909905,-0.666629,2.588577,0.088475,-2.481844,-2.517725
3,3,2.055948,-0.039039,1.826668,-2.630403,-0.638002,0.664687,-0.757260,2.369401,3.547932,...,-1.557832,2.384457,0.288551,-1.150473,5.312439,-0.788347,2.741491,-0.362241,-2.403488,-2.006749
4,1,1.993814,0.626228,2.123430,-2.568481,-0.670118,0.824960,-1.366554,2.413033,3.727258,...,-0.553639,2.447007,0.261426,-1.733082,6.362278,-0.951700,2.869695,0.627546,-2.230731,-1.442407
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2,1.709061,-0.116455,2.036383,-2.597020,-0.907886,1.038571,-1.326351,2.699232,3.346574,...,0.416196,2.138269,0.317000,-1.431819,5.351776,-0.871853,2.306323,-0.127611,-2.273822,-2.037293
76,3,1.924288,-0.588345,1.924117,-2.668794,-0.883919,0.861714,-1.248688,2.542697,3.353333,...,-1.162991,2.277523,0.128654,-1.593110,4.561308,-1.063216,2.701439,-1.160671,-2.339794,-2.290268
77,1,1.742533,0.454757,1.896593,-2.945253,-0.559005,-0.043019,-1.089511,2.342422,3.456428,...,-0.203662,2.077902,0.469032,-1.649820,5.165113,-1.112130,2.472960,-0.623667,-2.633995,-1.530874
78,3,1.757113,-0.066469,2.199332,-2.381653,-0.945429,0.230355,-1.862197,2.310520,3.475208,...,-1.706191,2.278381,0.462650,-1.017330,3.822980,-1.289053,2.385955,-1.525282,-2.259702,-1.834159
79,2,1.767550,0.266439,2.002653,-2.824913,-0.253299,0.653584,-1.282841,2.412166,3.395280,...,0.035107,2.618756,-0.050118,-0.839769,5.676709,-1.013659,3.374325,-1.333573,-2.479321,-2.037251

## Split Data into Train, Test and Ensemble

In [6]:
from sklearn.model_selection import train_test_split

target_synth_train_comb_cont, target_synth_test_cont = train_test_split(
    target_synth_data_cont,
    train_size = num_samples_target + samples_target_ensemble,
    test_size = samples_target_test
)

target_synth_train_comb_cat, target_synth_test_cat = train_test_split(
    target_synth_data_cat,
    train_size = num_samples_target + samples_target_ensemble,
    test_size = samples_target_test,
    stratify = target_synth_data_cat['response'] # crucial or else random forest might break due to partition not representing all classes.
)

target_synth_train_cont, target_synth_train_ensemble_cont = train_test_split(
    target_synth_train_comb_cont,
    train_size = num_samples_target,
    test_size = samples_target_ensemble
)

target_synth_train_cat, target_synth_train_ensemble_cat = train_test_split(
    target_synth_train_comb_cat,
    train_size = num_samples_target,
    test_size = samples_target_ensemble,
    stratify = target_synth_train_comb_cat['response'] # crucial or else random forest might break due to partition not representing all classes.
)

## Creata Datacontainer Objects

In [7]:
from omicstl.simulation_utils.data_utils import DatasetContainer
datasets_cont = DatasetContainer(
	source_data=source_synth_data_cont,
	target_data=target_synth_train_cont,
    target_ensemble_data=target_synth_train_ensemble_cont,
	target_test_data=[target_synth_test_cont]
)
datasets_cont.set_response_column("response") # Identify response column

datasets_cat = DatasetContainer(
	source_data=source_synth_data_cat,
	target_data=target_synth_train_cat,
    target_ensemble_data=target_synth_train_ensemble_cat,
	target_test_data=[target_synth_test_cat]
)
datasets_cat.set_response_column("response") # Identify response column

## Model Fitting

In [8]:
param_grid = {
	"dropout": [0.25, 0.5],
	"n_latent_dims": [2],
	"hidden_dim_base": [6],
	"lr": [0.01, 0.001],
	"source_epochs": [1000],
	"target_epochs": [1000],
	"freeze": ["none"],
	"weight_decay": [1e-4, 1e-2],
	"gamma": [1, 2, 3]
}

In [9]:
import torch
from torch import device
import random
from omicstl.simulation_utils.model_utils import fit_dl_model

random.seed(42)
torch.manual_seed(42)
out, mult_vae_cont_model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, mult_vae_cat_model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,0.308862,0.267662,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0100,1.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,0.304005,0.238659,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,1.0

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,NaN,NaN,0.32,0.155152,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,NaN,NaN,0.32,0.155152,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0

In [10]:
random.seed(42)
torch.manual_seed(42)
out, mult_mlp_cont_model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, mult_mlp_cat_model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,0.306508,0.237087,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,0.454468,0.360483,NaN,NaN,...,0.50,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,3.0

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,NaN,NaN,0.36,0.351111,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.01,1.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,NaN,NaN,0.32,0.233026,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.01,3.0

In [11]:
from omicstl.r_utils import set_seed
from omicstl.simulation_utils.model_utils import fit_rf_model

random.seed(42)
out, rf_cont_model = fit_rf_model(datasets_cont)
display(out)

random.seed(42)
set_seed(42)
out, rf_cat_model = fit_rf_model(datasets_cat)
display(out)

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall,roc_auc
0,None,None,test_0,rf,pred_source_full,target,0.319087,0.256904,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,test_0,rf,pred_source_full_val,target,0.319087,0.256904,NaN,NaN,NaN,NaN,NaN,NaN
2,None,None,test_0,rf,pred_0_full,target,0.310448,0.249799,NaN,NaN,NaN,NaN,NaN,NaN
3,None,None,test_0,rf,pred_0_full_val,target,0.310448,0.249799,NaN,NaN,NaN,NaN,NaN,NaN
4,None,None,test_0,rf,pred_1_full,target,0.294970,0.239944,NaN,NaN,NaN,NaN,NaN,NaN
5,None,None,test_0,rf,pred_1_full_val,target,0.294970,0.239944,NaN,NaN,NaN,NaN,NaN,NaN
6,None,None,test_0,rf,pred_2_full,target,0.292596,0.231941,NaN,NaN,NaN,NaN,NaN,NaN
7,None,None,test_0,rf,pred_2_full_val,target,0.292596,0.231941,NaN,NaN,NaN,NaN,NaN,NaN
8,None,None,test_0,rf,pred_3_full,target,0.311506,0.248743,NaN,NaN,NaN,NaN,NaN,NaN
9,None,None,test_0,rf,pred_3_full_val,target,0.311506,0.248743,NaN,NaN,NaN,NaN,NaN,NaN
10,None,None,test_0,rf,pred_ensemble_full,target,0.298545,0.240919,NaN,NaN,NaN,NaN,NaN,NaN
11,None,None,test_0,rf,pred_ensemble_full_val,target,0.298266,0.240867,NaN,NaN,NaN,NaN,NaN,NaN

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall,roc_auc
0,None,None,test_0,rf,pred_source_full,target,NaN,NaN,0.36,0.349333,0.050171,0.384791,0.36,0.815882
1,None,None,test_0,rf,pred_source_full_val,target,NaN,NaN,0.36,0.332406,0.060800,0.413651,0.36,0.815882
2,None,None,test_0,rf,pred_0_full,target,NaN,NaN,0.28,0.228571,-0.070558,0.194462,0.28,0.670294
3,None,None,test_0,rf,pred_0_full_val,target,NaN,NaN,0.36,0.354667,0.055925,0.442667,0.36,0.670294
4,None,None,test_0,rf,pred_1_full,target,NaN,NaN,0.36,0.330667,0.046812,0.325714,0.36,0.868088
5,None,None,test_0,rf,pred_1_full_val,target,NaN,NaN,0.44,0.436912,0.157007,0.435429,0.44,0.868088
6,None,None,test_0,rf,pred_2_full,target,NaN,NaN,0.48,0.426222,0.246578,0.434667,0.48,0.842794
7,None,None,test_0,rf,pred_2_full_val,target,NaN,NaN,0.60,0.580952,0.426452,0.616879,0.60,0.842794
8,None,None,test_0,rf,pred_3_full,target,NaN,NaN,0.48,0.449351,0.242802,0.482667,0.48,0.833382
9,None,None,test_0,rf,pred_3_full_val,target,NaN,NaN,0.40,0.309630,0.146921,0.374737,0.40,0.833382
10,None,None,test_0,rf,pred_ensemble_full,target,NaN,NaN,0.56,0.524420,0.368037,0.554857,0.56,0.825147
11,None,None,test_0,rf,pred_ensemble_full_val,target,NaN,NaN,0.44,0.414957,0.190885,0.505143,0.44,0.822794

### Predictions

In [ ]:
from omicstl.simulation_utils.model_utils import predict_dl_model

# Create "new" data by shuffling existing values
new_synth_data_cont = source_synth_data_cont.iloc[:, 1:]
values = new_synth_data_cont.values.flatten()
np.random.shuffle(values)
new_synth_data_cont = pd.DataFrame(
    values.reshape(new_synth_data_cont.shape),
    columns=new_synth_data_cont.columns
)

new_synth_data_cat = source_synth_data_cat.iloc[:, 1:]
values = new_synth_data_cat.values.flatten()
np.random.shuffle(values)
new_synth_data_cat = pd.DataFrame(
    values.reshape(new_synth_data_cat.shape),
    columns=new_synth_data_cat.columns
)

# Get predicted response values on the new data
out = predict_dl_model(mult_vae_cont_model, new_synth_data_cont)
display(out)

out = predict_dl_model(mult_vae_cat_model, new_synth_data_cat)
display(out)

out = predict_dl_model(mult_mlp_cont_model, new_synth_data_cont)
display(out)

out = predict_dl_model(mult_mlp_cat_model, new_synth_data_cat)
display(out)

In [ ]:
from omicstl.simulation_utils.model_utils import predict_rf_model

out = predict_rf_model(rf_cont_model, new_synth_data_cont)
display(pd.DataFrame(out))

out = predict_rf_model(rf_cat_model, new_synth_data_cat)
display(pd.DataFrame(out))