# omicsTL - Transfer Learning Example

<div>
<img src="images/tl_arch1.png" width="500" style="background-color: white;"/>
</div>

This notebook demonstrates the use of omicsTL to create a transfer learning model for synthetic data generated using real data objects.

We will start by loading the required functions.

In [1]:
import warnings
warnings.filterwarnings("always")

from omicstl.simulation_utils.data_generation import response_function, generate_synth_data

The first step is to generate two synthetic data frames. We will be using two different viral datasets with aligned features as the real data sources for the simulated data. The first will represent the source data that we are training the "base" model on, and the second will represent the target data.

For this example we will create two pairs of synthetic data frames, one with a continuous response and one with a categorical response.

In [2]:
import pandas as pd
import numpy as np

source_real_data_path = "data/source_data_real.csv"
target_real_data_path = "data/target_data_real.csv"

source_real_data = pd.read_csv(source_real_data_path, index_col=0)
target_real_data = pd.read_csv(target_real_data_path, index_col=0)

# Non-trivial continuous response function
response_fn = response_function("tanh(df[, 2]) + df[, 1] * df[, ncol(df)] ^ 2")

num_features = 100
num_samples_source = 100
num_samples_target = 50
samples_target_test = 25
samples_target_ensemble = 5

In [3]:
# Continuous response

source_synth_data_cont, _, _ = generate_synth_data(
    data = source_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_source, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 # signal to noise ratio
)

target_synth_data_cont, _, _ = generate_synth_data(
    data = target_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_target + samples_target_test + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 # signal to noise ratio
)

display(source_synth_data_cont)
display(target_synth_data_cont)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,5.759515,2.340357,-3.702338,0.222190,2.370815,1.676313,-2.521341,-0.012336,3.343996,5.377136,...,1.093478,2.798459,4.306979,1.305513,-1.617649,-0.781249,-2.150191,5.181717,0.702785,1.489934
1,6.033749,2.638899,-3.995441,0.774667,2.174091,1.887284,-3.121093,0.110597,3.183873,4.849400,...,1.092568,2.838965,4.093730,1.187012,-1.410990,-0.740475,-2.099870,5.269571,0.223589,1.436670
2,-0.765455,2.486532,-3.190165,0.805228,1.359534,1.980707,-3.055416,1.011304,3.267104,5.181898,...,0.815634,3.011187,3.880805,0.980154,-1.580756,-0.332498,-2.182057,5.055795,0.191128,0.975681
3,1.560679,3.011851,-3.529548,0.563088,2.518338,2.117688,-3.298657,0.977181,3.254119,4.881603,...,0.924902,2.631137,4.022563,1.166586,-1.282516,-0.691128,-2.380152,5.051904,0.163555,0.832894
4,2.682922,2.960700,-3.853872,0.264953,2.423814,1.446679,-2.392054,0.595139,3.350380,4.821565,...,1.011104,2.731299,4.073421,1.209269,-1.701396,-0.825532,-2.233457,5.064963,0.918777,1.445459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,9.491534,2.264441,-4.143817,1.108069,2.893949,1.828999,-2.226662,0.666059,3.325022,3.968278,...,0.751905,2.946935,3.716751,1.099945,-1.442296,-0.394732,-1.944214,5.081597,0.701012,2.001641
96,3.353009,2.255115,-3.958036,1.003347,1.443206,1.671773,-2.722542,0.575921,3.301068,4.861967,...,1.315159,2.683288,4.227242,1.099442,-1.620424,-0.529235,-2.192524,4.846709,1.432832,1.551220
97,5.007670,2.403752,-4.026748,0.875650,2.495603,1.833510,-3.091919,0.249608,3.364026,5.047663,...,0.615900,2.732390,3.877459,1.195734,-1.499562,-0.542027,-2.023303,4.718691,0.755004,1.682132
98,3.827236,2.869439,-3.960206,0.949779,2.667576,1.814312,-3.085998,0.039154,3.311940,4.546697,...,1.169776,2.913418,4.213087,0.755452,-1.810641,-0.716817,-2.263685,4.940579,0.457989,1.004443
99,2.709430,2.492178,-3.635465,0.464090,2.059701,2.174061,-2.795079,0.424948,3.298258,5.336325,...,1.270508,2.994694,3.967626,1.254808,-1.191144,-0.461408,-2.919175,5.081179,0.219956,1.271089

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,-12.700476,-1.150007,-0.059643,-2.888946,5.484700,0.424376,1.812684,-1.324211,1.822032,1.092232,...,-0.604465,2.879806,5.531917,5.143388,-1.517243,0.763320,2.186526,2.729718,-0.921800,2.711299
1,-15.635416,-1.820048,0.245575,-2.864446,5.640988,0.867164,3.320213,-0.296496,2.933916,2.032600,...,0.626426,4.997093,6.050242,4.462087,-0.635647,1.551609,1.772227,4.720035,-0.673207,2.609092
2,-5.829101,-1.577978,0.032847,-2.931291,5.635079,0.115640,2.818033,-2.065516,2.138857,1.427381,...,0.585299,4.284381,5.826679,5.259224,-1.194576,0.764477,2.379473,3.214320,-1.008531,3.083326
3,-16.939620,-1.440839,-0.162681,-2.163125,5.643945,0.717887,2.081273,-0.375875,1.782149,1.140970,...,0.499002,4.266470,5.996702,4.904221,-0.614637,1.362503,1.766622,4.146122,-0.721675,3.305393
4,-10.928741,-1.105233,-0.087879,-2.715949,5.328908,0.916765,1.915866,-0.678329,1.516040,1.329112,...,0.567110,3.691231,5.587221,5.187950,-1.360375,1.357295,1.972800,2.094901,-0.853071,3.161211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,-20.746103,-1.798562,0.122354,-2.333472,5.342404,1.021124,2.409545,-0.992005,2.337015,1.415067,...,-0.674481,4.771625,5.228399,4.593059,-0.658006,1.213636,1.803909,3.455718,-0.523454,3.264349
76,-8.034078,-1.361802,-0.134213,-2.855270,5.304252,1.838988,3.114439,-1.331208,2.156703,0.746108,...,-0.466832,3.714725,5.902312,5.007673,-1.364909,1.387889,1.629415,4.986470,-0.601132,2.771453
77,-15.701261,-1.808350,-0.286080,-2.179509,5.515532,1.156862,3.098343,-0.085015,2.632268,1.086320,...,-0.150737,4.335557,5.668784,4.845418,-1.360375,0.999002,1.797295,1.788483,-1.122969,3.077994
78,-10.630891,-1.227414,0.201125,-2.716441,5.323638,0.359773,2.589536,-1.299966,1.896898,1.137581,...,-0.107320,4.238526,6.458387,5.140927,-0.764369,1.112973,1.929243,4.945156,-0.844997,3.509335
79,-14.491507,-1.546988,0.072740,-2.834226,5.223610,1.777384,2.696587,-1.116918,2.060664,1.268486,...,0.736126,3.428623,5.657404,5.665593,-0.693049,1.668099,2.566814,2.405413,-0.819325,2.848573

In [4]:
# Categorical response

source_synth_data_cat, _, _ = generate_synth_data(
    data = source_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_source + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    snr = 1, # signal to noise ratio
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

target_synth_data_cat, _, _ = generate_synth_data(
    data = target_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_target + samples_target_test + samples_target_ensemble, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 ,# signal to noise ratio
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

display(source_synth_data_cat)
display(target_synth_data_cat)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2.0,0.675673,2.484680,-1.414837,4.227080,-0.852358,1.168394,-0.113928,1.507452,-3.288314,...,1.131851,2.915107,-1.223187,1.091035,2.409785,2.740305,1.606017,-2.890515,1.631351,-2.973796
1,2.0,0.699718,2.344813,-1.267741,4.956075,-0.732426,1.883098,-0.192221,-1.537678,-3.071380,...,1.222918,3.054182,-1.039339,1.705855,2.561674,2.605567,1.983747,-2.530622,2.122498,-2.731028
2,2.0,0.758523,2.505292,-1.388187,7.019353,-0.773569,1.402090,-0.282705,2.823681,-2.400786,...,1.292470,2.969154,-1.161943,0.481340,2.602663,2.524307,1.674104,-2.828812,2.309894,-2.850077
3,3.0,1.138091,1.925685,-0.905337,5.069044,-0.685365,1.657266,-0.017870,0.876339,-1.796262,...,1.259388,2.728932,-1.244012,1.231516,2.247501,2.043888,1.865603,-2.823244,2.203240,-2.814513
4,3.0,1.145811,2.110514,-1.681958,5.531842,-0.738441,1.606730,-0.046976,2.647002,-2.219326,...,1.199156,3.391828,-1.033946,1.451810,2.854254,2.505956,1.427519,-2.441731,2.399876,-3.087653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1.0,0.763014,2.241377,-1.580532,5.875096,-0.637806,1.552433,-0.191510,-1.805249,-2.742622,...,1.245025,2.888724,-1.213417,1.489291,2.916019,2.347436,1.785997,-2.972235,2.063151,-2.862951
101,1.0,0.570175,2.703493,-1.296434,5.835019,-0.737959,1.789888,-0.069809,-1.332085,-2.742622,...,1.012427,3.240278,-1.081442,1.380572,2.479911,2.338049,1.561572,-2.257818,1.827744,-2.871938
102,2.0,0.770564,2.450122,-1.026783,7.894339,-0.832515,1.222381,-0.041873,1.629752,-1.976398,...,1.136034,2.799090,-1.089890,0.509731,2.712252,1.944853,1.779670,-2.431381,2.361354,-2.821125
103,3.0,0.683485,2.390878,-1.404157,4.704561,-0.860509,1.889323,-0.229806,1.557542,-2.828106,...,1.377371,2.879027,-1.175264,1.541507,2.615336,2.048336,1.606944,-2.256777,1.578876,-3.046308
104,1.0,0.085091,2.460303,-0.864873,6.560613,-0.663906,1.919983,0.244775,0.236879,-1.971336,...,1.075607,3.281762,-1.155502,1.578340,2.753952,2.586164,1.865958,-2.438457,2.025235,-2.611887

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,1.0,2.126302,1.201218,2.582909,-0.627438,3.243717,0.254858,2.971577,-0.016380,1.430204,...,-1.023865,0.167885,-0.129793,-2.269894,-0.900990,0.433261,5.585850,-1.522713,5.992317,9.464943
1,3.0,2.960488,1.212554,2.388188,0.955678,3.206667,0.537432,2.901975,0.385240,1.260222,...,-1.172076,-1.251164,-0.300590,-1.108433,-1.297488,-0.018264,5.553869,-1.044983,5.488951,10.448268
2,2.0,3.191200,0.735380,2.958260,0.270622,3.599198,0.464085,2.966016,0.602183,1.372922,...,-1.337887,0.431074,-0.321353,-2.263010,-1.096126,0.185563,5.567673,-0.978413,5.489503,9.982645
3,1.0,2.250697,1.614338,2.650404,1.023134,2.903879,0.065761,2.799125,-0.375968,0.358849,...,-1.502118,0.460009,-0.012214,-1.548227,-1.089783,0.236419,5.517653,-1.117111,6.456025,10.092525
4,1.0,2.962167,0.801170,3.075969,1.502775,2.950969,0.272935,2.894959,0.461408,2.604694,...,-2.251060,-0.187941,-0.047995,-2.087216,-0.902778,-0.120035,5.415138,-0.919058,6.029791,10.371585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,3.0,2.940422,2.102573,2.867713,0.336185,3.116660,0.109546,2.923516,-0.156030,1.514244,...,-2.525599,-0.232602,-0.698705,-2.756726,-1.021076,-0.046541,5.669047,-1.287767,5.956329,10.183689
76,3.0,3.254365,1.551809,2.824026,0.625537,3.115564,0.090355,2.820830,0.311642,1.672265,...,-0.676769,0.123564,-0.413631,-1.682797,-1.021325,-0.023133,5.384059,-1.084211,5.897617,10.349478
77,3.0,3.090196,1.364166,2.829476,1.178666,3.120287,0.196706,2.962213,0.955112,1.825531,...,-1.707860,0.559628,-0.055183,-2.930694,-1.060624,-0.186796,5.593098,-1.270657,7.030593,9.853405
78,3.0,3.304092,0.474659,2.468085,0.470932,2.663739,0.321910,3.026481,1.203518,2.759107,...,-1.069338,0.139067,-1.050919,-2.603585,-0.805726,0.004698,5.650343,-0.834395,5.218741,9.560344
79,1.0,2.688742,1.210767,2.819018,0.445660,2.553220,0.437454,2.895016,0.411619,2.027709,...,-1.405964,0.633686,-0.509080,-2.357416,-0.785525,-0.396434,5.245348,-0.954055,6.192692,9.553488

In [5]:
# Set response column name

source_synth_data_cont.rename(columns={source_synth_data_cont.columns[0]: 'response'}, inplace=True)
target_synth_data_cont.rename(columns={target_synth_data_cont.columns[0]: 'response'}, inplace=True)
display(source_synth_data_cont)
display(target_synth_data_cont)

source_synth_data_cat.rename(columns={source_synth_data_cat.columns[0]: 'response'}, inplace=True)
target_synth_data_cat.rename(columns={target_synth_data_cat.columns[0]: 'response'}, inplace=True)
source_synth_data_cat = source_synth_data_cat.astype({"response": np.int64})
target_synth_data_cat = target_synth_data_cat.astype({"response": np.int64})
display(source_synth_data_cat)
display(target_synth_data_cat)

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,5.759515,2.340357,-3.702338,0.222190,2.370815,1.676313,-2.521341,-0.012336,3.343996,5.377136,...,1.093478,2.798459,4.306979,1.305513,-1.617649,-0.781249,-2.150191,5.181717,0.702785,1.489934
1,6.033749,2.638899,-3.995441,0.774667,2.174091,1.887284,-3.121093,0.110597,3.183873,4.849400,...,1.092568,2.838965,4.093730,1.187012,-1.410990,-0.740475,-2.099870,5.269571,0.223589,1.436670
2,-0.765455,2.486532,-3.190165,0.805228,1.359534,1.980707,-3.055416,1.011304,3.267104,5.181898,...,0.815634,3.011187,3.880805,0.980154,-1.580756,-0.332498,-2.182057,5.055795,0.191128,0.975681
3,1.560679,3.011851,-3.529548,0.563088,2.518338,2.117688,-3.298657,0.977181,3.254119,4.881603,...,0.924902,2.631137,4.022563,1.166586,-1.282516,-0.691128,-2.380152,5.051904,0.163555,0.832894
4,2.682922,2.960700,-3.853872,0.264953,2.423814,1.446679,-2.392054,0.595139,3.350380,4.821565,...,1.011104,2.731299,4.073421,1.209269,-1.701396,-0.825532,-2.233457,5.064963,0.918777,1.445459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,9.491534,2.264441,-4.143817,1.108069,2.893949,1.828999,-2.226662,0.666059,3.325022,3.968278,...,0.751905,2.946935,3.716751,1.099945,-1.442296,-0.394732,-1.944214,5.081597,0.701012,2.001641
96,3.353009,2.255115,-3.958036,1.003347,1.443206,1.671773,-2.722542,0.575921,3.301068,4.861967,...,1.315159,2.683288,4.227242,1.099442,-1.620424,-0.529235,-2.192524,4.846709,1.432832,1.551220
97,5.007670,2.403752,-4.026748,0.875650,2.495603,1.833510,-3.091919,0.249608,3.364026,5.047663,...,0.615900,2.732390,3.877459,1.195734,-1.499562,-0.542027,-2.023303,4.718691,0.755004,1.682132
98,3.827236,2.869439,-3.960206,0.949779,2.667576,1.814312,-3.085998,0.039154,3.311940,4.546697,...,1.169776,2.913418,4.213087,0.755452,-1.810641,-0.716817,-2.263685,4.940579,0.457989,1.004443
99,2.709430,2.492178,-3.635465,0.464090,2.059701,2.174061,-2.795079,0.424948,3.298258,5.336325,...,1.270508,2.994694,3.967626,1.254808,-1.191144,-0.461408,-2.919175,5.081179,0.219956,1.271089

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,-12.700476,-1.150007,-0.059643,-2.888946,5.484700,0.424376,1.812684,-1.324211,1.822032,1.092232,...,-0.604465,2.879806,5.531917,5.143388,-1.517243,0.763320,2.186526,2.729718,-0.921800,2.711299
1,-15.635416,-1.820048,0.245575,-2.864446,5.640988,0.867164,3.320213,-0.296496,2.933916,2.032600,...,0.626426,4.997093,6.050242,4.462087,-0.635647,1.551609,1.772227,4.720035,-0.673207,2.609092
2,-5.829101,-1.577978,0.032847,-2.931291,5.635079,0.115640,2.818033,-2.065516,2.138857,1.427381,...,0.585299,4.284381,5.826679,5.259224,-1.194576,0.764477,2.379473,3.214320,-1.008531,3.083326
3,-16.939620,-1.440839,-0.162681,-2.163125,5.643945,0.717887,2.081273,-0.375875,1.782149,1.140970,...,0.499002,4.266470,5.996702,4.904221,-0.614637,1.362503,1.766622,4.146122,-0.721675,3.305393
4,-10.928741,-1.105233,-0.087879,-2.715949,5.328908,0.916765,1.915866,-0.678329,1.516040,1.329112,...,0.567110,3.691231,5.587221,5.187950,-1.360375,1.357295,1.972800,2.094901,-0.853071,3.161211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,-20.746103,-1.798562,0.122354,-2.333472,5.342404,1.021124,2.409545,-0.992005,2.337015,1.415067,...,-0.674481,4.771625,5.228399,4.593059,-0.658006,1.213636,1.803909,3.455718,-0.523454,3.264349
76,-8.034078,-1.361802,-0.134213,-2.855270,5.304252,1.838988,3.114439,-1.331208,2.156703,0.746108,...,-0.466832,3.714725,5.902312,5.007673,-1.364909,1.387889,1.629415,4.986470,-0.601132,2.771453
77,-15.701261,-1.808350,-0.286080,-2.179509,5.515532,1.156862,3.098343,-0.085015,2.632268,1.086320,...,-0.150737,4.335557,5.668784,4.845418,-1.360375,0.999002,1.797295,1.788483,-1.122969,3.077994
78,-10.630891,-1.227414,0.201125,-2.716441,5.323638,0.359773,2.589536,-1.299966,1.896898,1.137581,...,-0.107320,4.238526,6.458387,5.140927,-0.764369,1.112973,1.929243,4.945156,-0.844997,3.509335
79,-14.491507,-1.546988,0.072740,-2.834226,5.223610,1.777384,2.696587,-1.116918,2.060664,1.268486,...,0.736126,3.428623,5.657404,5.665593,-0.693049,1.668099,2.566814,2.405413,-0.819325,2.848573

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2,0.675673,2.484680,-1.414837,4.227080,-0.852358,1.168394,-0.113928,1.507452,-3.288314,...,1.131851,2.915107,-1.223187,1.091035,2.409785,2.740305,1.606017,-2.890515,1.631351,-2.973796
1,2,0.699718,2.344813,-1.267741,4.956075,-0.732426,1.883098,-0.192221,-1.537678,-3.071380,...,1.222918,3.054182,-1.039339,1.705855,2.561674,2.605567,1.983747,-2.530622,2.122498,-2.731028
2,2,0.758523,2.505292,-1.388187,7.019353,-0.773569,1.402090,-0.282705,2.823681,-2.400786,...,1.292470,2.969154,-1.161943,0.481340,2.602663,2.524307,1.674104,-2.828812,2.309894,-2.850077
3,3,1.138091,1.925685,-0.905337,5.069044,-0.685365,1.657266,-0.017870,0.876339,-1.796262,...,1.259388,2.728932,-1.244012,1.231516,2.247501,2.043888,1.865603,-2.823244,2.203240,-2.814513
4,3,1.145811,2.110514,-1.681958,5.531842,-0.738441,1.606730,-0.046976,2.647002,-2.219326,...,1.199156,3.391828,-1.033946,1.451810,2.854254,2.505956,1.427519,-2.441731,2.399876,-3.087653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1,0.763014,2.241377,-1.580532,5.875096,-0.637806,1.552433,-0.191510,-1.805249,-2.742622,...,1.245025,2.888724,-1.213417,1.489291,2.916019,2.347436,1.785997,-2.972235,2.063151,-2.862951
101,1,0.570175,2.703493,-1.296434,5.835019,-0.737959,1.789888,-0.069809,-1.332085,-2.742622,...,1.012427,3.240278,-1.081442,1.380572,2.479911,2.338049,1.561572,-2.257818,1.827744,-2.871938
102,2,0.770564,2.450122,-1.026783,7.894339,-0.832515,1.222381,-0.041873,1.629752,-1.976398,...,1.136034,2.799090,-1.089890,0.509731,2.712252,1.944853,1.779670,-2.431381,2.361354,-2.821125
103,3,0.683485,2.390878,-1.404157,4.704561,-0.860509,1.889323,-0.229806,1.557542,-2.828106,...,1.377371,2.879027,-1.175264,1.541507,2.615336,2.048336,1.606944,-2.256777,1.578876,-3.046308
104,1,0.085091,2.460303,-0.864873,6.560613,-0.663906,1.919983,0.244775,0.236879,-1.971336,...,1.075607,3.281762,-1.155502,1.578340,2.753952,2.586164,1.865958,-2.438457,2.025235,-2.611887

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,1,2.126302,1.201218,2.582909,-0.627438,3.243717,0.254858,2.971577,-0.016380,1.430204,...,-1.023865,0.167885,-0.129793,-2.269894,-0.900990,0.433261,5.585850,-1.522713,5.992317,9.464943
1,3,2.960488,1.212554,2.388188,0.955678,3.206667,0.537432,2.901975,0.385240,1.260222,...,-1.172076,-1.251164,-0.300590,-1.108433,-1.297488,-0.018264,5.553869,-1.044983,5.488951,10.448268
2,2,3.191200,0.735380,2.958260,0.270622,3.599198,0.464085,2.966016,0.602183,1.372922,...,-1.337887,0.431074,-0.321353,-2.263010,-1.096126,0.185563,5.567673,-0.978413,5.489503,9.982645
3,1,2.250697,1.614338,2.650404,1.023134,2.903879,0.065761,2.799125,-0.375968,0.358849,...,-1.502118,0.460009,-0.012214,-1.548227,-1.089783,0.236419,5.517653,-1.117111,6.456025,10.092525
4,1,2.962167,0.801170,3.075969,1.502775,2.950969,0.272935,2.894959,0.461408,2.604694,...,-2.251060,-0.187941,-0.047995,-2.087216,-0.902778,-0.120035,5.415138,-0.919058,6.029791,10.371585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,3,2.940422,2.102573,2.867713,0.336185,3.116660,0.109546,2.923516,-0.156030,1.514244,...,-2.525599,-0.232602,-0.698705,-2.756726,-1.021076,-0.046541,5.669047,-1.287767,5.956329,10.183689
76,3,3.254365,1.551809,2.824026,0.625537,3.115564,0.090355,2.820830,0.311642,1.672265,...,-0.676769,0.123564,-0.413631,-1.682797,-1.021325,-0.023133,5.384059,-1.084211,5.897617,10.349478
77,3,3.090196,1.364166,2.829476,1.178666,3.120287,0.196706,2.962213,0.955112,1.825531,...,-1.707860,0.559628,-0.055183,-2.930694,-1.060624,-0.186796,5.593098,-1.270657,7.030593,9.853405
78,3,3.304092,0.474659,2.468085,0.470932,2.663739,0.321910,3.026481,1.203518,2.759107,...,-1.069338,0.139067,-1.050919,-2.603585,-0.805726,0.004698,5.650343,-0.834395,5.218741,9.560344
79,1,2.688742,1.210767,2.819018,0.445660,2.553220,0.437454,2.895016,0.411619,2.027709,...,-1.405964,0.633686,-0.509080,-2.357416,-0.785525,-0.396434,5.245348,-0.954055,6.192692,9.553488

Then we can split the target data into train and test sets.

In [6]:
from sklearn.model_selection import train_test_split

target_synth_train_comb_cont, target_synth_test_cont = train_test_split(
    target_synth_data_cont,
    train_size = num_samples_target + samples_target_ensemble,
    test_size = samples_target_test
)

target_synth_train_comb_cat, target_synth_test_cat = train_test_split(
    target_synth_data_cat,
    train_size = num_samples_target + samples_target_ensemble,
    test_size = samples_target_test,
    stratify = target_synth_data_cat['response'] # crucial or else random forest might break due to partition not representing all classes.
)

target_synth_train_cont, target_synth_train_ensemble_cont = train_test_split(
    target_synth_train_comb_cont,
    train_size = num_samples_target,
    test_size = samples_target_ensemble
)

target_synth_train_cat, target_synth_train_ensemble_cat = train_test_split(
    target_synth_train_comb_cat,
    train_size = num_samples_target,
    test_size = samples_target_ensemble,
    stratify = target_synth_train_comb_cat['response'] # crucial or else random forest might break due to partition not representing all classes.
)

The data is now ready to be used for transfer learning.

We provide a DatasetContainer helper class to keep the different datasets organized. Optionally, id_tuple can also be set which is used to label the scenario and replicate IDs if performing large scale simulation studies. These IDs are passed to the output after model fitting.

In [7]:
from omicstl.simulation_utils.data_utils import DatasetContainer
datasets_cont = DatasetContainer(
	source_data=source_synth_data_cont,
	target_data=target_synth_train_cont,
    target_ensemble_data=target_synth_train_ensemble_cont,
	target_test_data=[target_synth_test_cont]
)
datasets_cont.set_response_column("response") # Identify response column

datasets_cat = DatasetContainer(
	source_data=source_synth_data_cat,
	target_data=target_synth_train_cat,
    target_ensemble_data=target_synth_train_ensemble_cat,
	target_test_data=[target_synth_test_cat]
)
datasets_cat.set_response_column("response") # Identify response column

We enable automatic tuning over a parameter grid for both deep learning models:

In [8]:
param_grid = {
	"dropout": [0.25, 0.5],
	"n_latent_dims": [2],
	"hidden_dim_base": [6],
	"lr": [0.01, 0.001],
	"source_epochs": [1000],
	"target_epochs": [1000],
	"freeze": ["none"],
	"weight_decay": [1e-4, 1e-2],
	"gamma": [1, 2, 3]
}

Deep learning models can be fit using a DatasetContainer and parameter grid using fit_dl_model, which returns a dataframe with results, the trained transfer learning model, and the model trained on only the target dataset.

In [9]:
import torch
from torch import device
import random
from omicstl.simulation_utils.model_utils import fit_dl_model

random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1017: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,5.729428,4.188541,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0100,1.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,4.788606,3.945630,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,1.0

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1017: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,NaN,NaN,0.32,0.310366,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,3.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,NaN,NaN,0.36,0.190588,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0100,1.0

In [10]:
random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1017: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,4.771513,3.945835,NaN,NaN,...,0.50,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,4.740150,3.578454,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0100,2.0

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1017: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,NaN,NaN,0.32,0.318095,...,0.50,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,3.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,NaN,NaN,0.32,0.207515,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0100,2.0

The random forest based models can also be fit using a python interface to the R modeling code.

In [11]:
from omicstl.r_utils import set_seed
from omicstl.simulation_utils.model_utils import fit_rf_model

random.seed(42)
out, model = fit_rf_model(datasets_cont)
display(out)

random.seed(42)
set_seed(42)
out, model = fit_rf_model(datasets_cat)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall
0,None,None,test_0,rf,pred_source_full,target,14.161164,13.322826,NaN,NaN,NaN,NaN,NaN
1,None,None,test_0,rf,pred_source_full_val,target,14.161164,13.322826,NaN,NaN,NaN,NaN,NaN
2,None,None,test_0,rf,pred_0_full,target,4.490092,3.835710,NaN,NaN,NaN,NaN,NaN
3,None,None,test_0,rf,pred_0_full_val,target,4.490092,3.835710,NaN,NaN,NaN,NaN,NaN
4,None,None,test_0,rf,pred_1_full,target,4.074821,3.389548,NaN,NaN,NaN,NaN,NaN
5,None,None,test_0,rf,pred_1_full_val,target,4.074821,3.389548,NaN,NaN,NaN,NaN,NaN
6,None,None,test_0,rf,pred_2_full,target,4.505520,3.828904,NaN,NaN,NaN,NaN,NaN
7,None,None,test_0,rf,pred_2_full_val,target,4.505520,3.828904,NaN,NaN,NaN,NaN,NaN
8,None,None,test_0,rf,pred_3_full,target,4.498671,3.823756,NaN,NaN,NaN,NaN,NaN
9,None,None,test_0,rf,pred_3_full_val,target,4.498671,3.823756,NaN,NaN,NaN,NaN,NaN
10,None,None,test_0,rf,pred_ensemble_full,target,4.351756,3.701577,NaN,NaN,NaN,NaN,NaN
11,None,None,test_0,rf,pred_ensemble_full_val,target,4.353216,3.704326,NaN,NaN,NaN,NaN,NaN

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1216: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall,roc_auc
0,None,None,test_0,rf,pred_source_full,target,NaN,NaN,0.36,0.190588,0.000000,0.129600,0.36,0.437426
1,None,None,test_0,rf,pred_source_full_val,target,NaN,NaN,0.36,0.190588,0.000000,0.129600,0.36,0.437426
2,None,None,test_0,rf,pred_0_full,target,NaN,NaN,0.24,0.238637,-0.156795,0.317231,0.24,0.485662
3,None,None,test_0,rf,pred_0_full_val,target,NaN,NaN,0.24,0.238637,-0.156795,0.317231,0.24,0.485662
4,None,None,test_0,rf,pred_1_full,target,NaN,NaN,0.32,0.326617,-0.024273,0.340000,0.32,0.621471
5,None,None,test_0,rf,pred_1_full_val,target,NaN,NaN,0.32,0.326617,-0.024273,0.340000,0.32,0.621471
6,None,None,test_0,rf,pred_2_full,target,NaN,NaN,0.40,0.402986,0.095847,0.426747,0.40,0.524412
7,None,None,test_0,rf,pred_2_full_val,target,NaN,NaN,0.40,0.402986,0.095847,0.426747,0.40,0.524412
8,None,None,test_0,rf,pred_3_full,target,NaN,NaN,0.28,0.302637,-0.091464,0.477231,0.28,0.452721
9,None,None,test_0,rf,pred_3_full_val,target,NaN,NaN,0.28,0.302637,-0.091464,0.477231,0.28,0.452721
10,None,None,test_0,rf,pred_ensemble_full,target,NaN,NaN,0.48,0.405974,0.253204,0.490526,0.48,0.542059
11,None,None,test_0,rf,pred_ensemble_full_val,target,NaN,NaN,0.48,0.414545,0.241998,0.500000,0.48,0.544559

Advanced users can also work directly with the base classes we provide for each TL model via TransferForest() and MultiViewModel().