# omicsTL - Transfer Learning Example

<div>
<img src="images/tl_arch1.png" width="500" style="background-color: white;"/>
</div>

This notebook demonstrates the use of omicsTL to create a transfer learning model for synthetic data generated using real data objects.

We will start by loading the required functions.

In [1]:
import warnings
warnings.filterwarnings("always")

from omicstl.simulation_utils.data_generation import response_function, generate_synth_data

The first step is to generate two synthetic data frames. We will be using two different viral datasets with aligned features as the real data sources for the simulated data. The first will represent the source data that we are training the "base" model on, and the second will represent the target data.

For this example we will create two pairs of synthetic data frames, one with a continuous response and one with a categorical response.

In [2]:
import pandas as pd
import numpy as np

source_real_data_path = "data/source_data_real.csv"
target_real_data_path = "data/target_data_real.csv"

source_real_data = pd.read_csv(source_real_data_path, index_col=0)
target_real_data = pd.read_csv(target_real_data_path, index_col=0)

# Non-trivial continuous response function
response_fn = response_function("tanh(df[, 2]) + df[, 1] * df[, ncol(df)] ^ 2")

num_features = 100
num_samples_source = 100
num_samples_target = 50
samples_target_test = 25

In [3]:
# Continuous response

source_synth_data_cont, _, _ = generate_synth_data(
    data = source_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_source, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 # signal to noise ratio
)

target_synth_data_cont, _, _ = generate_synth_data(
    data = target_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_target + samples_target_test, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 # signal to noise ratio
)

display(source_synth_data_cont)
display(target_synth_data_cont)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,-0.164189,0.728839,0.513009,1.737959,1.262245,0.213674,0.553496,1.741215,4.214248,8.400754,...,-0.235586,3.372158,0.465471,1.786222,-1.672215,6.810261,0.005557,2.250875,6.197050,0.664658
1,1.004733,0.536635,0.654216,2.290442,1.195273,-0.035464,0.264012,2.372805,4.562964,7.676885,...,-0.180579,3.452168,0.661561,1.211970,-1.862751,6.845817,0.722998,2.248053,6.177564,0.546287
2,-0.644756,0.719000,-0.360891,2.381854,0.232787,-0.214362,0.486034,2.967611,4.405193,8.372654,...,0.077318,3.366484,0.585151,2.191809,-2.019389,7.455440,0.938927,2.232379,6.274872,0.395548
3,1.390284,0.518577,1.014732,1.897802,0.494353,-0.292024,0.504375,1.981409,4.368233,8.694024,...,-0.200633,3.306626,0.426872,1.361315,-2.126426,6.972293,0.559814,2.267768,6.114769,0.625580
4,1.931303,0.872246,0.446673,2.122074,0.928410,-0.361520,0.565508,2.083242,4.495758,8.523781,...,-0.084292,3.300113,0.572763,1.232783,-1.869851,7.350051,0.333091,2.173303,6.256823,0.950323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.535726,0.540773,0.491054,1.924260,0.096728,-0.230453,0.282468,2.310017,4.205516,8.478027,...,-0.015105,3.325078,0.384035,2.224221,-1.834575,7.384647,0.523005,2.275186,6.122546,0.344522
96,1.170351,0.483009,0.330247,2.113315,0.520649,0.544783,0.633835,2.368749,4.403453,8.692141,...,0.020833,3.150415,0.527268,1.971183,-1.916830,7.440371,0.801925,2.187078,6.333440,0.720751
97,1.111972,0.577137,0.241558,1.834623,1.333914,0.036494,0.481931,1.959972,4.511020,7.923294,...,-0.068220,3.372045,0.335914,1.201449,-1.901891,6.839944,0.994021,1.928246,6.122354,0.970914
98,0.363695,0.542368,0.750311,2.073544,1.110912,-0.241839,0.411288,2.804279,4.324561,8.742001,...,-0.095807,3.149745,0.557675,0.746466,-2.176220,7.373942,0.796142,2.245065,6.063914,0.597422
99,1.792146,0.848153,0.986827,1.758734,0.023705,0.143500,0.438033,2.428281,4.538089,8.027410,...,0.098711,3.066740,0.371911,1.790254,-1.940310,6.703654,1.142350,2.182266,6.160707,0.505148

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2.405904,0.807132,3.153937,0.360929,-0.070699,-2.022765,-1.084318,0.110290,2.346569,-1.110856,...,-1.594385,-0.090060,0.049493,3.481210,-2.588912,0.537172,4.744705,1.267789,0.778164,1.645621
1,0.641904,0.498537,1.312039,-1.386743,0.320018,-2.131942,-1.754261,0.830079,2.129504,-0.862814,...,-2.029288,-0.881841,0.473149,3.412413,-2.502982,-0.053624,4.771556,0.729889,0.245104,2.731724
2,6.579773,1.101909,1.398594,-0.315313,-0.433006,-2.300145,-1.053091,0.689035,1.893629,-0.933425,...,-2.228323,-0.727369,-0.031341,3.994906,-2.196828,0.111638,4.558616,0.693916,0.413343,2.798582
3,9.423264,0.906809,2.346493,-0.450311,-0.610719,-2.185740,-0.892842,0.942400,1.908150,-0.477764,...,-2.027075,-1.081891,0.656206,3.762677,-2.186833,0.770614,4.692534,1.100272,0.368470,2.721124
4,5.068664,0.865465,1.825502,0.650950,-0.396687,-2.057339,-0.994912,1.107394,1.992629,-0.008971,...,-1.384092,-0.799536,0.168347,3.856295,-2.092627,0.118347,4.930133,1.507163,0.095276,1.609939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,10.013716,0.855380,1.143705,0.561943,-0.852951,-1.984198,-1.079881,0.436955,2.028719,-0.916978,...,-1.619716,-0.531128,0.220604,4.123140,-2.541446,0.174895,4.811437,0.967516,0.853402,2.729742
71,7.289318,0.745531,3.643147,-0.344834,0.118892,-2.230298,-0.016825,1.345017,2.215110,0.425685,...,-1.845165,0.129324,0.675424,3.534084,-2.504008,0.086411,4.791588,1.033787,0.355123,2.518137
72,12.839314,1.064716,2.767145,0.213888,-0.546944,-2.049701,-1.021710,0.682597,1.816838,-0.935783,...,-1.657436,0.322157,0.460852,4.285647,-1.783564,0.478573,4.806241,1.718018,0.097169,2.510764
73,6.370355,1.133348,1.719696,0.598363,-0.400103,-2.245125,-0.082898,0.675404,1.926354,-1.303822,...,-2.030834,-0.860461,0.458362,3.566454,-2.141413,0.123945,4.380277,1.203749,0.273441,2.511425
74,5.552917,0.684021,0.956968,0.671189,0.369402,-2.115700,-0.639232,1.219879,1.933663,-0.371656,...,-2.200903,0.064861,0.209345,3.623485,-2.158681,0.045182,4.754820,1.099863,0.094281,3.002021

In [4]:
# Categorical response

source_synth_data_cat, _, _ = generate_synth_data(
    data = source_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_source, # number of output samples
    response_fn = response_fn, # response function
    snr = 1, # signal to noise ratio
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

target_synth_data_cat, _, _ = generate_synth_data(
    data = target_real_data, # input data
    num_features = num_features, # number of output features
    num_samples = num_samples_target + samples_target_test, # number of output samples
    response_fn = response_fn, # response function
    snr = 1 ,# signal to noise ratio
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

display(source_synth_data_cat)
display(target_synth_data_cat)

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2.0,3.178834,-0.187361,3.877632,1.564765,3.748219,0.739920,1.522166,-2.094877,4.531976,...,1.173101,1.084535,0.610454,2.156648,4.846223,0.025100,2.034661,8.466996,-0.663534,4.763799
1,1.0,3.434782,-0.403149,3.915078,1.849003,3.209797,2.189553,-0.135098,-2.402558,4.164609,...,0.920412,0.524293,0.449098,2.083931,4.447045,-1.022175,1.951692,8.261737,-0.924049,4.560818
2,1.0,2.983779,-0.319978,4.144603,1.731883,3.446666,2.106425,2.500934,-2.956071,4.398707,...,1.839200,-0.123970,0.565989,2.170117,4.092517,0.571402,1.944530,8.015889,-0.858851,4.950848
3,3.0,3.204103,-0.679850,4.308990,1.698123,2.662155,0.585704,0.859373,-1.825152,3.642867,...,0.965118,0.015198,0.659446,2.177850,4.123629,1.059104,2.142127,8.892086,-0.685158,4.982849
4,1.0,3.277176,-0.618067,3.967586,1.411682,4.122332,1.289348,0.398472,-2.215922,4.054487,...,1.119247,-0.578200,0.405290,1.991539,4.543253,-2.274496,2.128435,8.578749,-0.466608,4.440719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1.0,2.852682,-0.575632,4.028518,1.445266,3.486523,1.846675,1.583373,-1.982585,4.448453,...,1.493948,-1.526026,0.574170,2.152483,4.552074,-0.092500,1.903598,8.153337,-0.796236,4.759323
96,3.0,3.515193,-0.477202,3.468325,0.988142,3.503186,0.605053,1.935699,-2.242687,4.199865,...,1.695989,-0.586276,0.525155,2.127013,4.462939,0.152804,2.117810,8.597413,-0.509087,5.042962
97,3.0,3.064445,-0.423211,4.027106,1.825274,3.414673,1.815917,0.704662,-2.487533,4.242527,...,1.256077,0.295397,0.398306,2.164490,4.504604,-0.178009,1.827783,8.075336,-0.630964,5.250998
98,2.0,3.187650,-0.443973,3.977208,2.025544,2.822830,0.944762,-0.098744,-2.071413,4.151947,...,1.715715,-0.198600,0.747648,2.147685,4.588213,1.521166,2.068172,8.193571,-1.077510,4.824786
99,1.0,3.121568,-0.382010,4.360016,1.759129,3.902435,1.634737,1.806325,-2.009788,4.486171,...,1.276292,0.883092,0.591281,1.985474,4.396591,-1.292937,2.190560,8.356004,-0.659949,4.932427

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,1.0,1.326962,-0.780565,0.000905,0.558553,-3.722608,-2.855470,0.802496,1.374315,4.905299,...,-1.872233,-0.608097,-3.328712,-1.742711,-2.189042,1.080154,-2.295462,3.229888,-1.732940,-0.013444
1,3.0,1.040333,-0.895245,0.041809,0.778586,-3.561205,-2.262083,1.328050,1.911121,5.007608,...,-2.186750,-1.397369,-3.338128,-2.208017,-2.191260,1.017451,-2.507741,3.346083,-1.796463,0.872543
2,2.0,1.431791,-0.977695,0.035918,0.824302,-3.271232,-1.439536,1.367324,1.430188,5.155944,...,-1.942391,-1.235160,-3.125285,-2.643938,-1.664812,0.885047,-2.340659,3.344284,-1.826421,-0.259707
3,1.0,0.975209,-0.671997,-0.285932,0.897055,-3.523672,-1.215052,0.705821,1.580313,5.118782,...,-1.617519,-0.835316,-3.448067,-2.315953,-1.932646,0.876211,-2.867504,3.243041,-1.719036,-0.398287
4,1.0,1.325269,-0.980964,-0.274193,0.732092,-3.631788,-1.537738,0.805276,2.330839,4.928009,...,-1.339353,-0.378257,-3.117352,-2.040188,-2.708779,1.018815,-2.246082,3.381822,-1.540726,0.029247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,3.0,1.038724,-0.506769,-0.289494,0.966159,-3.170657,-3.284137,0.633501,2.101508,5.337210,...,-1.882659,-0.868555,-3.369779,-2.176940,-1.933550,0.703943,-2.555352,3.477600,-2.176924,-0.804879
71,3.0,1.073804,-0.292223,0.155739,0.840003,-3.415553,-2.898656,0.342138,3.058539,5.011793,...,-1.525231,-1.274330,-3.410576,-2.534115,-1.946739,1.041147,-2.585835,3.514182,-2.412755,0.362677
72,1.0,1.374725,-0.907909,0.759296,0.994550,-2.978256,-1.458771,0.591901,1.620867,4.993080,...,-0.967940,-0.838128,-3.438641,-2.409738,-2.217549,1.266987,-2.495588,2.917736,-2.218179,0.699307
73,2.0,1.174986,-0.615485,-0.001662,0.755501,-3.566648,-2.332396,0.400981,2.849590,5.291643,...,-1.470459,-1.143210,-3.361642,-1.836473,-1.638852,1.172848,-2.810420,3.587943,-2.135582,0.246051
74,3.0,1.372120,-0.777893,0.189449,0.581553,-3.650843,-2.810449,0.581595,1.575798,5.305737,...,-1.618746,-0.860539,-3.616019,-2.719269,-2.099445,1.009098,-2.209159,3.261286,-1.384961,0.825988

In [5]:
# Set response column name

source_synth_data_cont.rename(columns={source_synth_data_cont.columns[0]: 'response'}, inplace=True)
target_synth_data_cont.rename(columns={target_synth_data_cont.columns[0]: 'response'}, inplace=True)
display(source_synth_data_cont)
display(target_synth_data_cont)

source_synth_data_cat.rename(columns={source_synth_data_cat.columns[0]: 'response'}, inplace=True)
target_synth_data_cat.rename(columns={target_synth_data_cat.columns[0]: 'response'}, inplace=True)
source_synth_data_cat = source_synth_data_cat.astype({"response": np.int64})
target_synth_data_cat = target_synth_data_cat.astype({"response": np.int64})
display(source_synth_data_cat)
display(target_synth_data_cat)

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,-0.164189,0.728839,0.513009,1.737959,1.262245,0.213674,0.553496,1.741215,4.214248,8.400754,...,-0.235586,3.372158,0.465471,1.786222,-1.672215,6.810261,0.005557,2.250875,6.197050,0.664658
1,1.004733,0.536635,0.654216,2.290442,1.195273,-0.035464,0.264012,2.372805,4.562964,7.676885,...,-0.180579,3.452168,0.661561,1.211970,-1.862751,6.845817,0.722998,2.248053,6.177564,0.546287
2,-0.644756,0.719000,-0.360891,2.381854,0.232787,-0.214362,0.486034,2.967611,4.405193,8.372654,...,0.077318,3.366484,0.585151,2.191809,-2.019389,7.455440,0.938927,2.232379,6.274872,0.395548
3,1.390284,0.518577,1.014732,1.897802,0.494353,-0.292024,0.504375,1.981409,4.368233,8.694024,...,-0.200633,3.306626,0.426872,1.361315,-2.126426,6.972293,0.559814,2.267768,6.114769,0.625580
4,1.931303,0.872246,0.446673,2.122074,0.928410,-0.361520,0.565508,2.083242,4.495758,8.523781,...,-0.084292,3.300113,0.572763,1.232783,-1.869851,7.350051,0.333091,2.173303,6.256823,0.950323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.535726,0.540773,0.491054,1.924260,0.096728,-0.230453,0.282468,2.310017,4.205516,8.478027,...,-0.015105,3.325078,0.384035,2.224221,-1.834575,7.384647,0.523005,2.275186,6.122546,0.344522
96,1.170351,0.483009,0.330247,2.113315,0.520649,0.544783,0.633835,2.368749,4.403453,8.692141,...,0.020833,3.150415,0.527268,1.971183,-1.916830,7.440371,0.801925,2.187078,6.333440,0.720751
97,1.111972,0.577137,0.241558,1.834623,1.333914,0.036494,0.481931,1.959972,4.511020,7.923294,...,-0.068220,3.372045,0.335914,1.201449,-1.901891,6.839944,0.994021,1.928246,6.122354,0.970914
98,0.363695,0.542368,0.750311,2.073544,1.110912,-0.241839,0.411288,2.804279,4.324561,8.742001,...,-0.095807,3.149745,0.557675,0.746466,-2.176220,7.373942,0.796142,2.245065,6.063914,0.597422
99,1.792146,0.848153,0.986827,1.758734,0.023705,0.143500,0.438033,2.428281,4.538089,8.027410,...,0.098711,3.066740,0.371911,1.790254,-1.940310,6.703654,1.142350,2.182266,6.160707,0.505148

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2.405904,0.807132,3.153937,0.360929,-0.070699,-2.022765,-1.084318,0.110290,2.346569,-1.110856,...,-1.594385,-0.090060,0.049493,3.481210,-2.588912,0.537172,4.744705,1.267789,0.778164,1.645621
1,0.641904,0.498537,1.312039,-1.386743,0.320018,-2.131942,-1.754261,0.830079,2.129504,-0.862814,...,-2.029288,-0.881841,0.473149,3.412413,-2.502982,-0.053624,4.771556,0.729889,0.245104,2.731724
2,6.579773,1.101909,1.398594,-0.315313,-0.433006,-2.300145,-1.053091,0.689035,1.893629,-0.933425,...,-2.228323,-0.727369,-0.031341,3.994906,-2.196828,0.111638,4.558616,0.693916,0.413343,2.798582
3,9.423264,0.906809,2.346493,-0.450311,-0.610719,-2.185740,-0.892842,0.942400,1.908150,-0.477764,...,-2.027075,-1.081891,0.656206,3.762677,-2.186833,0.770614,4.692534,1.100272,0.368470,2.721124
4,5.068664,0.865465,1.825502,0.650950,-0.396687,-2.057339,-0.994912,1.107394,1.992629,-0.008971,...,-1.384092,-0.799536,0.168347,3.856295,-2.092627,0.118347,4.930133,1.507163,0.095276,1.609939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,10.013716,0.855380,1.143705,0.561943,-0.852951,-1.984198,-1.079881,0.436955,2.028719,-0.916978,...,-1.619716,-0.531128,0.220604,4.123140,-2.541446,0.174895,4.811437,0.967516,0.853402,2.729742
71,7.289318,0.745531,3.643147,-0.344834,0.118892,-2.230298,-0.016825,1.345017,2.215110,0.425685,...,-1.845165,0.129324,0.675424,3.534084,-2.504008,0.086411,4.791588,1.033787,0.355123,2.518137
72,12.839314,1.064716,2.767145,0.213888,-0.546944,-2.049701,-1.021710,0.682597,1.816838,-0.935783,...,-1.657436,0.322157,0.460852,4.285647,-1.783564,0.478573,4.806241,1.718018,0.097169,2.510764
73,6.370355,1.133348,1.719696,0.598363,-0.400103,-2.245125,-0.082898,0.675404,1.926354,-1.303822,...,-2.030834,-0.860461,0.458362,3.566454,-2.141413,0.123945,4.380277,1.203749,0.273441,2.511425
74,5.552917,0.684021,0.956968,0.671189,0.369402,-2.115700,-0.639232,1.219879,1.933663,-0.371656,...,-2.200903,0.064861,0.209345,3.623485,-2.158681,0.045182,4.754820,1.099863,0.094281,3.002021

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,2,3.178834,-0.187361,3.877632,1.564765,3.748219,0.739920,1.522166,-2.094877,4.531976,...,1.173101,1.084535,0.610454,2.156648,4.846223,0.025100,2.034661,8.466996,-0.663534,4.763799
1,1,3.434782,-0.403149,3.915078,1.849003,3.209797,2.189553,-0.135098,-2.402558,4.164609,...,0.920412,0.524293,0.449098,2.083931,4.447045,-1.022175,1.951692,8.261737,-0.924049,4.560818
2,1,2.983779,-0.319978,4.144603,1.731883,3.446666,2.106425,2.500934,-2.956071,4.398707,...,1.839200,-0.123970,0.565989,2.170117,4.092517,0.571402,1.944530,8.015889,-0.858851,4.950848
3,3,3.204103,-0.679850,4.308990,1.698123,2.662155,0.585704,0.859373,-1.825152,3.642867,...,0.965118,0.015198,0.659446,2.177850,4.123629,1.059104,2.142127,8.892086,-0.685158,4.982849
4,1,3.277176,-0.618067,3.967586,1.411682,4.122332,1.289348,0.398472,-2.215922,4.054487,...,1.119247,-0.578200,0.405290,1.991539,4.543253,-2.274496,2.128435,8.578749,-0.466608,4.440719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,2.852682,-0.575632,4.028518,1.445266,3.486523,1.846675,1.583373,-1.982585,4.448453,...,1.493948,-1.526026,0.574170,2.152483,4.552074,-0.092500,1.903598,8.153337,-0.796236,4.759323
96,3,3.515193,-0.477202,3.468325,0.988142,3.503186,0.605053,1.935699,-2.242687,4.199865,...,1.695989,-0.586276,0.525155,2.127013,4.462939,0.152804,2.117810,8.597413,-0.509087,5.042962
97,3,3.064445,-0.423211,4.027106,1.825274,3.414673,1.815917,0.704662,-2.487533,4.242527,...,1.256077,0.295397,0.398306,2.164490,4.504604,-0.178009,1.827783,8.075336,-0.630964,5.250998
98,2,3.187650,-0.443973,3.977208,2.025544,2.822830,0.944762,-0.098744,-2.071413,4.151947,...,1.715715,-0.198600,0.747648,2.147685,4.588213,1.521166,2.068172,8.193571,-1.077510,4.824786
99,1,3.121568,-0.382010,4.360016,1.759129,3.902435,1.634737,1.806325,-2.009788,4.486171,...,1.276292,0.883092,0.591281,1.985474,4.396591,-1.292937,2.190560,8.356004,-0.659949,4.932427

,response,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,100
0,1,1.326962,-0.780565,0.000905,0.558553,-3.722608,-2.855470,0.802496,1.374315,4.905299,...,-1.872233,-0.608097,-3.328712,-1.742711,-2.189042,1.080154,-2.295462,3.229888,-1.732940,-0.013444
1,3,1.040333,-0.895245,0.041809,0.778586,-3.561205,-2.262083,1.328050,1.911121,5.007608,...,-2.186750,-1.397369,-3.338128,-2.208017,-2.191260,1.017451,-2.507741,3.346083,-1.796463,0.872543
2,2,1.431791,-0.977695,0.035918,0.824302,-3.271232,-1.439536,1.367324,1.430188,5.155944,...,-1.942391,-1.235160,-3.125285,-2.643938,-1.664812,0.885047,-2.340659,3.344284,-1.826421,-0.259707
3,1,0.975209,-0.671997,-0.285932,0.897055,-3.523672,-1.215052,0.705821,1.580313,5.118782,...,-1.617519,-0.835316,-3.448067,-2.315953,-1.932646,0.876211,-2.867504,3.243041,-1.719036,-0.398287
4,1,1.325269,-0.980964,-0.274193,0.732092,-3.631788,-1.537738,0.805276,2.330839,4.928009,...,-1.339353,-0.378257,-3.117352,-2.040188,-2.708779,1.018815,-2.246082,3.381822,-1.540726,0.029247
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,3,1.038724,-0.506769,-0.289494,0.966159,-3.170657,-3.284137,0.633501,2.101508,5.337210,...,-1.882659,-0.868555,-3.369779,-2.176940,-1.933550,0.703943,-2.555352,3.477600,-2.176924,-0.804879
71,3,1.073804,-0.292223,0.155739,0.840003,-3.415553,-2.898656,0.342138,3.058539,5.011793,...,-1.525231,-1.274330,-3.410576,-2.534115,-1.946739,1.041147,-2.585835,3.514182,-2.412755,0.362677
72,1,1.374725,-0.907909,0.759296,0.994550,-2.978256,-1.458771,0.591901,1.620867,4.993080,...,-0.967940,-0.838128,-3.438641,-2.409738,-2.217549,1.266987,-2.495588,2.917736,-2.218179,0.699307
73,2,1.174986,-0.615485,-0.001662,0.755501,-3.566648,-2.332396,0.400981,2.849590,5.291643,...,-1.470459,-1.143210,-3.361642,-1.836473,-1.638852,1.172848,-2.810420,3.587943,-2.135582,0.246051
74,3,1.372120,-0.777893,0.189449,0.581553,-3.650843,-2.810449,0.581595,1.575798,5.305737,...,-1.618746,-0.860539,-3.616019,-2.719269,-2.099445,1.009098,-2.209159,3.261286,-1.384961,0.825988

Then we can split the target data into train and test sets.

In [6]:
from sklearn.model_selection import train_test_split

target_synth_train_cont, target_synth_test_cont = train_test_split(
    target_synth_data_cont,
    train_size = num_samples_target,
    test_size = samples_target_test
)

target_synth_train_cat, target_synth_test_cat = train_test_split(
    target_synth_data_cat,
    train_size = num_samples_target,
    test_size = samples_target_test
)

The data is now ready to be used for transfer learning.

We provide a DatasetContainer helper class to keep the different datasets organized. Optionally, id_tuple can also be set which is used to label the scenario and replicate IDs if performing large scale simulation studies. These IDs are passed to the output after model fitting.

In [7]:
from omicstl.simulation_utils.data_utils import DatasetContainer
datasets_cont = DatasetContainer(
	source_data=source_synth_data_cont,
	target_data=target_synth_train_cont,
	target_test_data=[target_synth_test_cont]
)
datasets_cont.set_response_column("response") # Identify response column

datasets_cat = DatasetContainer(
	source_data=source_synth_data_cat,
	target_data=target_synth_train_cat,
	target_test_data=[target_synth_test_cat]
)
datasets_cat.set_response_column("response") # Identify response column

We enable automatic tuning over a parameter grid for both deep learning models:

In [8]:
param_grid = {
	"dropout": [0.25, 0.5],
	"n_latent_dims": [2],
	"hidden_dim_base": [6],
	"lr": [0.01, 0.001],
	"source_epochs": [1000],
	"target_epochs": [1000],
	"freeze": ["none"],
	"weight_decay": [1e-4, 1e-2],
	"gamma": [1, 2, 3]
}

Deep learning models can be fit using a DatasetContainer and parameter grid using fit_dl_model, which returns a dataframe with results, the trained transfer learning model, and the model trained on only the target dataset.

In [9]:
import torch
from torch import device
import random
from omicstl.simulation_utils.model_utils import fit_dl_model
import importlib
import sys
importlib.reload(sys.modules["omicstl.simulation_utils.model_utils"])
from omicstl.simulation_utils.model_utils import fit_dl_model


random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:959: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,3.789582,3.131033,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,1.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,3.539853,2.893315,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,3.0

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:959: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,NaN,NaN,0.24,0.171641,...,0.50,6.0,2.0,1000.0,1000.0,none,12.0,0.001,0.0100,3.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,NaN,NaN,0.32,0.298936,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.010,0.0001,3.0

In [10]:
random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:959: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,3.205818,2.623186,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0100,2.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,3.745446,3.241092,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,1.0

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:959: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,NaN,NaN,0.24,0.221813,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,NaN,NaN,0.20,0.121143,...,0.50,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0

The random forest based models can also be fit using a python interface to the R modeling code.

In [ ]:
from omicstl.transfer_forest import load_r_functions
from omicstl.simulation_utils.model_utils import fit_rf_model
import importlib
import sys
importlib.reload(sys.modules["omicstl.transfer_forest"])
from omicstl.transfer_forest import TransferForest
importlib.reload(sys.modules["omicstl.simulation_utils.model_utils"])
from omicstl.simulation_utils.model_utils import fit_rf_model

load_r_functions()

#random.seed(42)
#out, model = fit_rf_model(datasets_cont)
#display(out)

random.seed(42)
out, model = fit_rf_model(datasets_cat)
display(out)

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1087: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall
0,None,None,test_0,rf,pred_0,target,3.128138,2.505578,NaN,NaN,NaN,NaN,NaN
1,None,None,test_0,rf,pred_1,target,2.753672,2.168906,NaN,NaN,NaN,NaN,NaN
2,None,None,test_0,rf,pred_2,target,6.835464,6.369672,NaN,NaN,NaN,NaN,NaN
3,None,None,test_0,rf,pred_3,target,3.057265,2.521764,NaN,NaN,NaN,NaN,NaN
4,None,None,test_0,rf,pred_ensemble,target,1.315126,1.102381,NaN,NaN,NaN,NaN,NaN

/opt/venv/lib/python3.12/site-packages/omicstl/simulation_utils/model_utils.py:1087: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall
0,None,None,test_0,rf,pred_0,target,NaN,NaN,0.40,0.273623,NaN,0.208000,0.40
1,None,None,test_0,rf,pred_1,target,NaN,NaN,0.40,0.319694,NaN,0.673287,0.40
2,None,None,test_0,rf,pred_2,target,NaN,NaN,0.48,0.329143,NaN,0.250435,0.48
3,None,None,test_0,rf,pred_3,target,NaN,NaN,0.24,0.151485,NaN,0.121111,0.24

Advanced users can also work directly with the base classes we provide for each TL model via TransferForest() and MultiViewModel().