## Import Core Utilities functions

In [1]:
import warnings
warnings.filterwarnings("always")

from omicstl.simulation_utils.data_generation import response_function, generate_synth_data_pca

## Load Data

In [2]:
import pandas as pd
import numpy as np

source_real_data_path = "data/source_data_real.csv"
target_real_data_path = "data/target_data_real.csv"

source_real_data = pd.read_csv(source_real_data_path, index_col=0)
target_real_data = pd.read_csv(target_real_data_path, index_col=0)

# Non-trivial continuous response function
response_fn = response_function("tanh(df[, 2]) + df[, 1] * df[, ncol(df)] ^ 2")

num_features = 100
num_samples_source = 100
num_samples_target = 50
samples_target_test = 25
samples_target_ensemble = 5

## Generate Linked Synthetic Datasets using PCA approach

In [4]:
# Continuous response

source_synth_data_cont, target_synth_data_cont, _, _ = generate_synth_data_pca(
    source_data = source_real_data,  # real source data
    target_data = target_real_data,  # real target data
    num_samples_source = num_samples_source,  # number of synthetic source samples
    num_samples_target = num_samples_target + samples_target_test + samples_target_ensemble,  # number of synthetic target samples
    response_fn = response_fn,  # response function
    snr = 1,  # signal to noise ratio
    num_features = num_features  # number of output features
)

display(source_synth_data_cont)
display(target_synth_data_cont)

,response,AT2B4_HUMAN,WDR1_HUMAN,KCD12_HUMAN,FUMH_HUMAN,RS15A_HUMAN,ABHDB_HUMAN,HMGB3_HUMAN,MAOX_HUMAN,HNRPU_HUMAN,...,SPE39_HUMAN,TMED1_HUMAN,PTBP1_HUMAN,HGS_HUMAN,COPE_HUMAN,UBA6_HUMAN,GFPT1_HUMAN,LC7L2_HUMAN,GRP75_HUMAN,TPM3_HUMAN
1,-0.835290,-1.663912,-1.580456,-1.372087,3.175607,3.340929,-1.335659,0.428090,-0.216676,2.149899,...,-0.597364,0.146707,-1.247110,0.525583,0.041075,2.929861,-1.024172,0.788255,2.857523,-0.056794
2,-1.175978,-2.026295,-1.485811,-1.003618,3.207358,3.175171,-1.339184,-0.150829,-0.058257,2.179530,...,-0.700560,-0.052813,-1.143603,0.524158,0.087681,2.959907,-0.817077,1.260286,2.842276,0.343584
3,-1.244775,-2.130438,-1.984812,-1.568539,2.964364,3.338403,-1.959379,0.490018,-0.586321,2.404064,...,-1.095518,-0.466679,-1.561414,0.105186,1.134431,2.497327,-1.341984,0.097519,2.667156,-0.508287
4,-0.751166,-1.618147,-1.437445,-1.037362,3.176802,3.432526,-1.052380,0.529613,0.198482,2.080430,...,-0.306202,0.216797,-1.032484,0.174800,0.100282,2.995376,-0.895703,0.908697,2.892656,0.149879
5,-2.197777,-1.700949,-1.547231,-1.140814,3.300940,3.427375,-1.058529,0.609941,0.812242,1.718800,...,-0.796694,0.415394,-1.100363,-0.537062,-0.283402,2.849894,-0.816389,1.457273,2.907139,0.584741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,-1.578486,-2.080267,-2.194813,-2.093735,3.001964,3.206657,-2.329913,0.522639,-0.412291,2.209858,...,-1.698730,0.049325,-1.877270,-0.302649,0.979309,2.314105,-1.494791,0.111381,2.712836,-0.511991
97,-0.877145,-1.740635,-1.813706,-1.412707,3.000557,3.706973,-1.425478,0.791837,0.135004,2.112319,...,-0.639644,0.076659,-1.253167,-0.490548,0.825837,2.600265,-1.365363,0.027331,2.799120,-0.385725
98,-1.095176,-1.888140,-1.583049,-1.098651,3.173974,3.299767,-1.303989,0.461515,-0.172438,2.195532,...,-0.645653,-0.299811,-1.188026,0.423605,0.193775,2.872630,-0.879482,1.049463,2.774155,0.130172
99,-1.879321,-1.924868,-1.967237,-1.590663,2.944404,3.449479,-1.834792,0.836406,-0.269790,2.305214,...,-0.847061,-0.117529,-1.541578,-0.300555,1.271384,2.563617,-1.347334,-0.061401,2.723076,-0.562957
100,-0.794610,-1.864408,-1.846499,-1.668838,3.197031,3.202324,-1.740550,0.593151,0.105670,1.971765,...,-1.326071,0.255374,-1.527967,-0.240306,0.196078,2.617520,-1.079967,0.933609,2.819381,0.102689

,response,AT2B4_HUMAN,WDR1_HUMAN,KCD12_HUMAN,FUMH_HUMAN,RS15A_HUMAN,ABHDB_HUMAN,HMGB3_HUMAN,MAOX_HUMAN,HNRPU_HUMAN,...,SPE39_HUMAN,TMED1_HUMAN,PTBP1_HUMAN,HGS_HUMAN,COPE_HUMAN,UBA6_HUMAN,GFPT1_HUMAN,LC7L2_HUMAN,GRP75_HUMAN,TPM3_HUMAN
1,-6.699926,-1.707342,2.795227,3.789450,2.525998,-0.102859,-2.322675,-1.143267,-0.678423,5.159542,...,-4.588888,-1.294908,3.329852,1.397885,-0.108988,-1.794361,-1.653323,-1.861139,3.281511,2.217870
2,-6.446365,-2.390728,3.430744,4.189687,2.608786,-0.210744,-3.236531,0.381299,-0.609657,4.905852,...,-4.055566,-0.812812,3.470017,1.125154,0.250341,-1.566478,-1.861610,-0.423179,3.045395,1.880744
3,-7.167057,-1.811301,2.745597,3.767279,2.573712,0.325744,-2.668030,-0.833101,-0.851662,5.211968,...,-4.490392,-1.017111,3.401657,1.454103,-0.128111,-1.719010,-1.758451,-1.441253,3.285821,2.074139
4,-4.372842,-0.692607,2.285812,3.409171,2.521572,-0.070500,-1.971172,-1.583099,-0.964669,5.663792,...,-4.557304,-0.654457,3.000513,2.021487,-0.425956,-1.489938,-1.012014,-1.971073,3.635164,2.575898
5,-13.429806,-2.421354,3.176065,4.014476,2.796999,-0.365309,-3.250050,0.769116,-0.843486,4.946154,...,-4.706367,-1.979445,3.501455,1.263450,0.212649,-1.944327,-1.795217,-1.053148,3.075600,2.246998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,-5.366733,-1.295328,2.562043,3.615248,2.587701,-0.329326,-2.033604,-1.313922,-0.751787,5.302091,...,-4.810149,-1.765151,3.264848,1.705946,-0.257100,-1.921608,-1.496838,-2.491411,3.459264,2.559714
77,-3.963344,-1.440570,3.039808,3.790451,2.558484,-0.606507,-1.960815,-1.051745,-0.489999,5.149541,...,-4.424152,-0.781035,3.257144,1.252562,0.096716,-1.456010,-1.069512,-2.173669,3.337821,2.381698
78,-6.208077,-1.607212,2.681077,3.689675,2.565521,0.034567,-2.817415,-0.830359,-0.964237,5.373876,...,-4.493846,-1.204637,3.324394,1.768211,-0.007156,-1.834002,-1.874797,-1.774375,3.426890,2.163851
79,-7.289371,-1.874098,2.704974,3.572443,2.737081,0.319073,-3.130470,-0.504777,-1.305624,5.469426,...,-4.684951,-1.129579,3.511099,1.754836,0.366639,-1.738854,-1.714409,-2.234476,3.449419,2.098603
80,-4.472933,-1.182855,2.451353,3.327321,2.729782,-0.305709,-2.377831,-0.416720,-1.031051,5.474255,...,-5.090161,-1.125979,3.076692,1.486191,0.048318,-1.667051,-0.856564,-2.279700,3.466545,2.608133

In [5]:
# Categorical response

source_synth_data_cat, target_synth_data_cat, _, _ = generate_synth_data_pca(
    source_data = source_real_data,  # real source data
    target_data = target_real_data,  # real target data
    num_samples_source = num_samples_source + samples_target_ensemble,  # number of synthetic source samples
    num_samples_target = num_samples_target + samples_target_test + samples_target_ensemble,  # number of synthetic target samples
    response_fn = response_fn,  # response function
    snr = 1,  # signal to noise ratio
    num_features = num_features,  # number of output features
    response_parameters={
        "ncats": 3,
        "quantile": "quantile"
    }
)

display(source_synth_data_cat)
display(target_synth_data_cat)

,response,TOIP1_HUMAN,K1C9_HUMAN,ERAP1_HUMAN,VATE1_HUMAN,PRPS1_HUMAN,ARF5_HUMAN,RAB13_HUMAN,A16A1_HUMAN,TIAR_HUMAN,...,ATPG_HUMAN,MATR3_HUMAN,RS12_HUMAN,SYG_HUMAN,TMED1_HUMAN,EF1A2_HUMAN,SFXN1_HUMAN,MAVS_HUMAN,PSD12_HUMAN,SH3L2_HUMAN
1,3.0,-0.489930,1.850209,2.428627,1.132589,-2.037770,3.426530,0.010223,-0.908693,-2.345589,...,2.471088,5.874121,6.098333,-2.057188,0.616897,-2.726200,2.928493,3.096430,-0.699817,0.049175
2,1.0,-0.706532,1.621117,2.496596,0.072501,0.203614,3.455173,-0.367148,-1.877862,-2.506342,...,2.183967,5.523896,5.482458,-2.062106,0.778165,-2.758273,3.130374,3.016003,-0.770838,0.175954
3,3.0,-1.063905,2.379583,2.010933,0.827179,-3.451003,3.839667,-0.296221,-0.867973,-2.764028,...,1.993338,5.413853,5.097342,-2.585656,-0.006778,-2.796713,2.833103,3.167113,-0.800871,-0.110453
4,1.0,-0.961008,2.249450,1.948947,0.589569,-2.504679,3.823365,-0.482836,-1.200563,-2.677471,...,1.916858,5.316030,5.025659,-2.395049,-0.060659,-2.747486,2.742044,3.001901,-0.824730,-0.014250
5,1.0,-0.899793,1.914335,2.115172,1.132520,-2.206432,3.306710,0.804871,-1.156455,-2.106318,...,2.662015,5.703662,5.844508,-2.233960,0.572547,-2.784659,2.618847,3.231676,-1.123155,0.080681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2.0,-0.796905,1.856723,2.425680,0.863311,-0.935531,3.216556,0.867427,-1.419437,-2.129396,...,2.770872,5.811982,5.978521,-2.159341,1.064323,-2.755709,2.916175,3.407673,-1.048973,0.148207
102,3.0,-1.085896,2.405518,1.712708,0.495361,-3.257739,3.918505,-0.927870,-1.309518,-2.779251,...,1.639924,5.113888,4.810978,-2.454504,-0.651273,-2.704320,2.455805,2.731855,-0.807489,-0.060852
103,3.0,-0.961125,1.897824,1.923204,0.650923,-2.162583,3.667656,-0.252433,-1.282634,-2.533177,...,2.054342,5.329848,5.121726,-2.260596,0.022727,-2.797273,2.677068,2.878806,-0.929345,0.059758
104,1.0,-1.034634,1.408974,1.941331,0.951400,-1.768273,3.275682,0.805895,-1.306309,-2.092962,...,2.587256,5.493692,5.484901,-2.153056,0.496173,-2.926329,2.587385,2.976672,-1.259881,0.150355
105,2.0,-1.115131,2.573599,2.031014,1.319845,-4.706510,3.608064,0.239788,-0.737464,-2.515328,...,2.326699,5.685699,5.747890,-2.684219,-0.029286,-2.654783,2.551441,3.295211,-0.892633,-0.204434

,response,TOIP1_HUMAN,K1C9_HUMAN,ERAP1_HUMAN,VATE1_HUMAN,PRPS1_HUMAN,ARF5_HUMAN,RAB13_HUMAN,A16A1_HUMAN,TIAR_HUMAN,...,ATPG_HUMAN,MATR3_HUMAN,RS12_HUMAN,SYG_HUMAN,TMED1_HUMAN,EF1A2_HUMAN,SFXN1_HUMAN,MAVS_HUMAN,PSD12_HUMAN,SH3L2_HUMAN
1,1.0,-0.246202,-1.116841,0.331895,-0.070879,-1.219647,-0.137320,-1.245216,-2.539051,-2.195702,...,1.699021,2.039127,2.601803,2.144198,-1.303349,-2.720650,0.124195,-2.895087,0.180072,-0.010557
2,3.0,0.031195,0.435175,0.379021,0.431254,-1.052954,-0.019189,-1.167201,-2.099501,-2.440353,...,2.091452,2.010558,2.728884,2.298616,-1.823253,-3.656749,0.355957,-2.899774,0.357301,0.540896
3,3.0,0.430475,0.464968,0.556544,-0.133487,-1.520604,-0.207166,-1.289942,-2.217422,-2.075907,...,2.391877,1.982607,3.061750,2.080349,-1.368180,-4.149294,1.007143,-2.895943,0.673452,-0.051898
4,3.0,-0.519476,-2.841220,0.596831,-0.140256,-0.747363,-0.391791,-1.087922,-2.250337,-1.933458,...,1.552133,2.145670,2.492330,2.094799,-1.118226,-3.046097,0.199091,-2.912541,-0.186954,-0.122228
5,3.0,0.456707,0.397251,0.631933,-0.545911,-1.691266,-0.433379,-1.431386,-2.596096,-1.857722,...,2.525845,1.916270,3.255480,1.954276,-1.408439,-4.352180,1.223693,-2.913009,0.757332,-0.421048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,1.0,-0.058814,-0.343409,0.068917,0.239001,-1.077503,0.170390,-0.737632,-2.330295,-2.195944,...,1.786438,2.072297,2.398497,2.208636,-0.841918,-2.148284,0.016489,-2.462522,0.184643,0.044269
77,3.0,0.443994,0.520806,0.106505,-0.060587,-1.697545,0.081876,-0.891436,-2.685230,-2.446004,...,2.312335,1.993555,2.877686,2.264346,-0.297196,-2.395122,0.662031,-2.981883,0.874668,0.008183
78,1.0,-0.524028,-2.198207,0.436799,-0.196467,-1.327424,-0.117518,-1.716680,-2.523181,-2.499681,...,1.193318,2.025796,2.463026,2.161576,-1.419304,-2.653630,-0.224170,-3.553906,0.088724,0.352998
79,2.0,0.233552,0.294327,0.295080,-0.295495,-1.519292,0.118425,-1.425301,-2.507295,-2.187286,...,1.776244,1.959503,2.717253,2.028263,-1.158725,-2.957287,0.275426,-2.875931,0.516893,0.021723
80,2.0,0.067712,-0.481173,0.471876,0.212269,-0.808330,0.197602,-1.164439,-1.652827,-2.189257,...,1.587182,2.086985,2.407215,2.125759,-1.289509,-3.489702,0.159258,-2.782023,0.113403,0.472678

## Standardized Response Column Naming

In [6]:
# Set response column name

source_synth_data_cont.rename(columns={source_synth_data_cont.columns[0]: 'response'}, inplace=True)
target_synth_data_cont.rename(columns={target_synth_data_cont.columns[0]: 'response'}, inplace=True)
display(source_synth_data_cont)
display(target_synth_data_cont)

source_synth_data_cat.rename(columns={source_synth_data_cat.columns[0]: 'response'}, inplace=True)
target_synth_data_cat.rename(columns={target_synth_data_cat.columns[0]: 'response'}, inplace=True)
source_synth_data_cat = source_synth_data_cat.astype({"response": np.int64})
target_synth_data_cat = target_synth_data_cat.astype({"response": np.int64})
display(source_synth_data_cat)
display(target_synth_data_cat)

,response,AT2B4_HUMAN,WDR1_HUMAN,KCD12_HUMAN,FUMH_HUMAN,RS15A_HUMAN,ABHDB_HUMAN,HMGB3_HUMAN,MAOX_HUMAN,HNRPU_HUMAN,...,SPE39_HUMAN,TMED1_HUMAN,PTBP1_HUMAN,HGS_HUMAN,COPE_HUMAN,UBA6_HUMAN,GFPT1_HUMAN,LC7L2_HUMAN,GRP75_HUMAN,TPM3_HUMAN
1,-0.835290,-1.663912,-1.580456,-1.372087,3.175607,3.340929,-1.335659,0.428090,-0.216676,2.149899,...,-0.597364,0.146707,-1.247110,0.525583,0.041075,2.929861,-1.024172,0.788255,2.857523,-0.056794
2,-1.175978,-2.026295,-1.485811,-1.003618,3.207358,3.175171,-1.339184,-0.150829,-0.058257,2.179530,...,-0.700560,-0.052813,-1.143603,0.524158,0.087681,2.959907,-0.817077,1.260286,2.842276,0.343584
3,-1.244775,-2.130438,-1.984812,-1.568539,2.964364,3.338403,-1.959379,0.490018,-0.586321,2.404064,...,-1.095518,-0.466679,-1.561414,0.105186,1.134431,2.497327,-1.341984,0.097519,2.667156,-0.508287
4,-0.751166,-1.618147,-1.437445,-1.037362,3.176802,3.432526,-1.052380,0.529613,0.198482,2.080430,...,-0.306202,0.216797,-1.032484,0.174800,0.100282,2.995376,-0.895703,0.908697,2.892656,0.149879
5,-2.197777,-1.700949,-1.547231,-1.140814,3.300940,3.427375,-1.058529,0.609941,0.812242,1.718800,...,-0.796694,0.415394,-1.100363,-0.537062,-0.283402,2.849894,-0.816389,1.457273,2.907139,0.584741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,-1.578486,-2.080267,-2.194813,-2.093735,3.001964,3.206657,-2.329913,0.522639,-0.412291,2.209858,...,-1.698730,0.049325,-1.877270,-0.302649,0.979309,2.314105,-1.494791,0.111381,2.712836,-0.511991
97,-0.877145,-1.740635,-1.813706,-1.412707,3.000557,3.706973,-1.425478,0.791837,0.135004,2.112319,...,-0.639644,0.076659,-1.253167,-0.490548,0.825837,2.600265,-1.365363,0.027331,2.799120,-0.385725
98,-1.095176,-1.888140,-1.583049,-1.098651,3.173974,3.299767,-1.303989,0.461515,-0.172438,2.195532,...,-0.645653,-0.299811,-1.188026,0.423605,0.193775,2.872630,-0.879482,1.049463,2.774155,0.130172
99,-1.879321,-1.924868,-1.967237,-1.590663,2.944404,3.449479,-1.834792,0.836406,-0.269790,2.305214,...,-0.847061,-0.117529,-1.541578,-0.300555,1.271384,2.563617,-1.347334,-0.061401,2.723076,-0.562957
100,-0.794610,-1.864408,-1.846499,-1.668838,3.197031,3.202324,-1.740550,0.593151,0.105670,1.971765,...,-1.326071,0.255374,-1.527967,-0.240306,0.196078,2.617520,-1.079967,0.933609,2.819381,0.102689

,response,AT2B4_HUMAN,WDR1_HUMAN,KCD12_HUMAN,FUMH_HUMAN,RS15A_HUMAN,ABHDB_HUMAN,HMGB3_HUMAN,MAOX_HUMAN,HNRPU_HUMAN,...,SPE39_HUMAN,TMED1_HUMAN,PTBP1_HUMAN,HGS_HUMAN,COPE_HUMAN,UBA6_HUMAN,GFPT1_HUMAN,LC7L2_HUMAN,GRP75_HUMAN,TPM3_HUMAN
1,-6.699926,-1.707342,2.795227,3.789450,2.525998,-0.102859,-2.322675,-1.143267,-0.678423,5.159542,...,-4.588888,-1.294908,3.329852,1.397885,-0.108988,-1.794361,-1.653323,-1.861139,3.281511,2.217870
2,-6.446365,-2.390728,3.430744,4.189687,2.608786,-0.210744,-3.236531,0.381299,-0.609657,4.905852,...,-4.055566,-0.812812,3.470017,1.125154,0.250341,-1.566478,-1.861610,-0.423179,3.045395,1.880744
3,-7.167057,-1.811301,2.745597,3.767279,2.573712,0.325744,-2.668030,-0.833101,-0.851662,5.211968,...,-4.490392,-1.017111,3.401657,1.454103,-0.128111,-1.719010,-1.758451,-1.441253,3.285821,2.074139
4,-4.372842,-0.692607,2.285812,3.409171,2.521572,-0.070500,-1.971172,-1.583099,-0.964669,5.663792,...,-4.557304,-0.654457,3.000513,2.021487,-0.425956,-1.489938,-1.012014,-1.971073,3.635164,2.575898
5,-13.429806,-2.421354,3.176065,4.014476,2.796999,-0.365309,-3.250050,0.769116,-0.843486,4.946154,...,-4.706367,-1.979445,3.501455,1.263450,0.212649,-1.944327,-1.795217,-1.053148,3.075600,2.246998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,-5.366733,-1.295328,2.562043,3.615248,2.587701,-0.329326,-2.033604,-1.313922,-0.751787,5.302091,...,-4.810149,-1.765151,3.264848,1.705946,-0.257100,-1.921608,-1.496838,-2.491411,3.459264,2.559714
77,-3.963344,-1.440570,3.039808,3.790451,2.558484,-0.606507,-1.960815,-1.051745,-0.489999,5.149541,...,-4.424152,-0.781035,3.257144,1.252562,0.096716,-1.456010,-1.069512,-2.173669,3.337821,2.381698
78,-6.208077,-1.607212,2.681077,3.689675,2.565521,0.034567,-2.817415,-0.830359,-0.964237,5.373876,...,-4.493846,-1.204637,3.324394,1.768211,-0.007156,-1.834002,-1.874797,-1.774375,3.426890,2.163851
79,-7.289371,-1.874098,2.704974,3.572443,2.737081,0.319073,-3.130470,-0.504777,-1.305624,5.469426,...,-4.684951,-1.129579,3.511099,1.754836,0.366639,-1.738854,-1.714409,-2.234476,3.449419,2.098603
80,-4.472933,-1.182855,2.451353,3.327321,2.729782,-0.305709,-2.377831,-0.416720,-1.031051,5.474255,...,-5.090161,-1.125979,3.076692,1.486191,0.048318,-1.667051,-0.856564,-2.279700,3.466545,2.608133

,response,TOIP1_HUMAN,K1C9_HUMAN,ERAP1_HUMAN,VATE1_HUMAN,PRPS1_HUMAN,ARF5_HUMAN,RAB13_HUMAN,A16A1_HUMAN,TIAR_HUMAN,...,ATPG_HUMAN,MATR3_HUMAN,RS12_HUMAN,SYG_HUMAN,TMED1_HUMAN,EF1A2_HUMAN,SFXN1_HUMAN,MAVS_HUMAN,PSD12_HUMAN,SH3L2_HUMAN
1,3,-0.489930,1.850209,2.428627,1.132589,-2.037770,3.426530,0.010223,-0.908693,-2.345589,...,2.471088,5.874121,6.098333,-2.057188,0.616897,-2.726200,2.928493,3.096430,-0.699817,0.049175
2,1,-0.706532,1.621117,2.496596,0.072501,0.203614,3.455173,-0.367148,-1.877862,-2.506342,...,2.183967,5.523896,5.482458,-2.062106,0.778165,-2.758273,3.130374,3.016003,-0.770838,0.175954
3,3,-1.063905,2.379583,2.010933,0.827179,-3.451003,3.839667,-0.296221,-0.867973,-2.764028,...,1.993338,5.413853,5.097342,-2.585656,-0.006778,-2.796713,2.833103,3.167113,-0.800871,-0.110453
4,1,-0.961008,2.249450,1.948947,0.589569,-2.504679,3.823365,-0.482836,-1.200563,-2.677471,...,1.916858,5.316030,5.025659,-2.395049,-0.060659,-2.747486,2.742044,3.001901,-0.824730,-0.014250
5,1,-0.899793,1.914335,2.115172,1.132520,-2.206432,3.306710,0.804871,-1.156455,-2.106318,...,2.662015,5.703662,5.844508,-2.233960,0.572547,-2.784659,2.618847,3.231676,-1.123155,0.080681
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2,-0.796905,1.856723,2.425680,0.863311,-0.935531,3.216556,0.867427,-1.419437,-2.129396,...,2.770872,5.811982,5.978521,-2.159341,1.064323,-2.755709,2.916175,3.407673,-1.048973,0.148207
102,3,-1.085896,2.405518,1.712708,0.495361,-3.257739,3.918505,-0.927870,-1.309518,-2.779251,...,1.639924,5.113888,4.810978,-2.454504,-0.651273,-2.704320,2.455805,2.731855,-0.807489,-0.060852
103,3,-0.961125,1.897824,1.923204,0.650923,-2.162583,3.667656,-0.252433,-1.282634,-2.533177,...,2.054342,5.329848,5.121726,-2.260596,0.022727,-2.797273,2.677068,2.878806,-0.929345,0.059758
104,1,-1.034634,1.408974,1.941331,0.951400,-1.768273,3.275682,0.805895,-1.306309,-2.092962,...,2.587256,5.493692,5.484901,-2.153056,0.496173,-2.926329,2.587385,2.976672,-1.259881,0.150355
105,2,-1.115131,2.573599,2.031014,1.319845,-4.706510,3.608064,0.239788,-0.737464,-2.515328,...,2.326699,5.685699,5.747890,-2.684219,-0.029286,-2.654783,2.551441,3.295211,-0.892633,-0.204434

,response,TOIP1_HUMAN,K1C9_HUMAN,ERAP1_HUMAN,VATE1_HUMAN,PRPS1_HUMAN,ARF5_HUMAN,RAB13_HUMAN,A16A1_HUMAN,TIAR_HUMAN,...,ATPG_HUMAN,MATR3_HUMAN,RS12_HUMAN,SYG_HUMAN,TMED1_HUMAN,EF1A2_HUMAN,SFXN1_HUMAN,MAVS_HUMAN,PSD12_HUMAN,SH3L2_HUMAN
1,1,-0.246202,-1.116841,0.331895,-0.070879,-1.219647,-0.137320,-1.245216,-2.539051,-2.195702,...,1.699021,2.039127,2.601803,2.144198,-1.303349,-2.720650,0.124195,-2.895087,0.180072,-0.010557
2,3,0.031195,0.435175,0.379021,0.431254,-1.052954,-0.019189,-1.167201,-2.099501,-2.440353,...,2.091452,2.010558,2.728884,2.298616,-1.823253,-3.656749,0.355957,-2.899774,0.357301,0.540896
3,3,0.430475,0.464968,0.556544,-0.133487,-1.520604,-0.207166,-1.289942,-2.217422,-2.075907,...,2.391877,1.982607,3.061750,2.080349,-1.368180,-4.149294,1.007143,-2.895943,0.673452,-0.051898
4,3,-0.519476,-2.841220,0.596831,-0.140256,-0.747363,-0.391791,-1.087922,-2.250337,-1.933458,...,1.552133,2.145670,2.492330,2.094799,-1.118226,-3.046097,0.199091,-2.912541,-0.186954,-0.122228
5,3,0.456707,0.397251,0.631933,-0.545911,-1.691266,-0.433379,-1.431386,-2.596096,-1.857722,...,2.525845,1.916270,3.255480,1.954276,-1.408439,-4.352180,1.223693,-2.913009,0.757332,-0.421048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,1,-0.058814,-0.343409,0.068917,0.239001,-1.077503,0.170390,-0.737632,-2.330295,-2.195944,...,1.786438,2.072297,2.398497,2.208636,-0.841918,-2.148284,0.016489,-2.462522,0.184643,0.044269
77,3,0.443994,0.520806,0.106505,-0.060587,-1.697545,0.081876,-0.891436,-2.685230,-2.446004,...,2.312335,1.993555,2.877686,2.264346,-0.297196,-2.395122,0.662031,-2.981883,0.874668,0.008183
78,1,-0.524028,-2.198207,0.436799,-0.196467,-1.327424,-0.117518,-1.716680,-2.523181,-2.499681,...,1.193318,2.025796,2.463026,2.161576,-1.419304,-2.653630,-0.224170,-3.553906,0.088724,0.352998
79,2,0.233552,0.294327,0.295080,-0.295495,-1.519292,0.118425,-1.425301,-2.507295,-2.187286,...,1.776244,1.959503,2.717253,2.028263,-1.158725,-2.957287,0.275426,-2.875931,0.516893,0.021723
80,2,0.067712,-0.481173,0.471876,0.212269,-0.808330,0.197602,-1.164439,-1.652827,-2.189257,...,1.587182,2.086985,2.407215,2.125759,-1.289509,-3.489702,0.159258,-2.782023,0.113403,0.472678

## Split Data into Train, Test and Ensemble

In [7]:
from sklearn.model_selection import train_test_split

target_synth_train_comb_cont, target_synth_test_cont = train_test_split(
    target_synth_data_cont,
    train_size = num_samples_target + samples_target_ensemble,
    test_size = samples_target_test
)

target_synth_train_comb_cat, target_synth_test_cat = train_test_split(
    target_synth_data_cat,
    train_size = num_samples_target + samples_target_ensemble,
    test_size = samples_target_test,
    stratify = target_synth_data_cat['response'] # crucial or else random forest might break due to partition not representing all classes.
)

target_synth_train_cont, target_synth_train_ensemble_cont = train_test_split(
    target_synth_train_comb_cont,
    train_size = num_samples_target,
    test_size = samples_target_ensemble
)

target_synth_train_cat, target_synth_train_ensemble_cat = train_test_split(
    target_synth_train_comb_cat,
    train_size = num_samples_target,
    test_size = samples_target_ensemble,
    stratify = target_synth_train_comb_cat['response'] # crucial or else random forest might break due to partition not representing all classes.
)

## Creata Datacontainer Objects

In [8]:
from omicstl.simulation_utils.data_utils import DatasetContainer
datasets_cont = DatasetContainer(
	source_data=source_synth_data_cont,
	target_data=target_synth_train_cont,
    target_ensemble_data=target_synth_train_ensemble_cont,
	target_test_data=[target_synth_test_cont]
)
datasets_cont.set_response_column("response") # Identify response column

datasets_cat = DatasetContainer(
	source_data=source_synth_data_cat,
	target_data=target_synth_train_cat,
    target_ensemble_data=target_synth_train_ensemble_cat,
	target_test_data=[target_synth_test_cat]
)
datasets_cat.set_response_column("response") # Identify response column

## Model Fitting

In [9]:
param_grid = {
	"dropout": [0.25, 0.5],
	"n_latent_dims": [2],
	"hidden_dim_base": [6],
	"lr": [0.01, 0.001],
	"source_epochs": [1000],
	"target_epochs": [1000],
	"freeze": ["none"],
	"weight_decay": [1e-4, 1e-2],
	"gamma": [1, 2, 3]
}

In [10]:
import torch
from torch import device
import random
from omicstl.simulation_utils.model_utils import fit_dl_model

random.seed(42)
torch.manual_seed(42)
out, mult_vae_cont_model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, mult_vae_cat_model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_vae",
	device("cpu"),
	param_grid
)
display(out)

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,2.158898,1.609762,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.01,1.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,2.235903,1.701618,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.01,2.0

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_vae,mult_vae,target,NaN,NaN,0.52,0.482667,...,0.50,6.0,2.0,1000.0,1000.0,none,12.0,0.001,0.0100,1.0
1,None,None,test_0,mult_vae,mult_vae,target_nosource,NaN,NaN,0.40,0.309333,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.010,0.0001,2.0

In [11]:
random.seed(42)
torch.manual_seed(42)
out, mult_mlp_cont_model, model_targetonly = fit_dl_model(
	datasets_cont,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

random.seed(42)
torch.manual_seed(42)
out, mult_mlp_cat_model, model_targetonly = fit_dl_model(
	datasets_cat,
	"mult_mlp",
	device("cpu"),
	param_grid
)
display(out)

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,2.754283,2.328721,NaN,NaN,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,1.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,3.190071,2.468241,NaN,NaN,...,0.50,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,3.0

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1039: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, test_results], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,...,dropout,hidden_dim_base,n_latent_dims,source_epochs,target_epochs,freeze,z_dim_base,lr,weight_decay,gamma
0,None,None,test_0,mult_mlp,mult_mlp,target,NaN,NaN,0.64,0.636356,...,0.50,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,1.0
1,None,None,test_0,mult_mlp,mult_mlp,target_nosource,NaN,NaN,0.64,0.623950,...,0.25,6.0,2.0,1000.0,1000.0,none,12.0,0.01,0.0001,2.0

In [12]:
from omicstl.r_utils import set_seed
from omicstl.simulation_utils.model_utils import fit_rf_model

random.seed(42)
out, rf_cont_model = fit_rf_model(datasets_cont)
display(out)

random.seed(42)
set_seed(42)
out, rf_cat_model = fit_rf_model(datasets_cat)
display(out)

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall,roc_auc
0,None,None,test_0,rf,pred_source_full,target,5.921431,5.497386,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,test_0,rf,pred_source_full_val,target,5.921431,5.497386,NaN,NaN,NaN,NaN,NaN,NaN
2,None,None,test_0,rf,pred_0_full,target,2.078176,1.627054,NaN,NaN,NaN,NaN,NaN,NaN
3,None,None,test_0,rf,pred_0_full_val,target,2.078176,1.627054,NaN,NaN,NaN,NaN,NaN,NaN
4,None,None,test_0,rf,pred_1_full,target,2.066001,1.611416,NaN,NaN,NaN,NaN,NaN,NaN
5,None,None,test_0,rf,pred_1_full_val,target,2.066001,1.611416,NaN,NaN,NaN,NaN,NaN,NaN
6,None,None,test_0,rf,pred_2_full,target,2.074827,1.599899,NaN,NaN,NaN,NaN,NaN,NaN
7,None,None,test_0,rf,pred_2_full_val,target,2.074827,1.599899,NaN,NaN,NaN,NaN,NaN,NaN
8,None,None,test_0,rf,pred_3_full,target,2.060150,1.599318,NaN,NaN,NaN,NaN,NaN,NaN
9,None,None,test_0,rf,pred_3_full_val,target,2.060150,1.599318,NaN,NaN,NaN,NaN,NaN,NaN
10,None,None,test_0,rf,pred_ensemble_full,target,2.067266,1.603473,NaN,NaN,NaN,NaN,NaN,NaN
11,None,None,test_0,rf,pred_ensemble_full_val,target,2.066995,1.602881,NaN,NaN,NaN,NaN,NaN,NaN

/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)
/workspaces/timed-hpc/src/omicstl/simulation_utils/model_utils.py:1237: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, pd.DataFrame([test_row])], ignore_index=True)

,scenario,replicate,split,model,model_type,model_id,rmse,mae,acc,f1,mcc,precision,recall,roc_auc
0,None,None,test_0,rf,pred_source_full,target,NaN,NaN,0.28,0.208627,-0.072227,0.171111,0.28,0.551765
1,None,None,test_0,rf,pred_source_full_val,target,NaN,NaN,0.28,0.193600,-0.074321,0.152941,0.28,0.551765
2,None,None,test_0,rf,pred_0_full,target,NaN,NaN,0.48,0.443810,0.264212,0.540000,0.48,0.810000
3,None,None,test_0,rf,pred_0_full_val,target,NaN,NaN,0.48,0.452308,0.286266,0.604444,0.48,0.810000
4,None,None,test_0,rf,pred_1_full,target,NaN,NaN,0.48,0.444103,0.242734,0.472308,0.48,0.832059
5,None,None,test_0,rf,pred_1_full_val,target,NaN,NaN,0.48,0.411667,0.256503,0.397143,0.48,0.832059
6,None,None,test_0,rf,pred_2_full,target,NaN,NaN,0.40,0.352411,0.129159,0.428000,0.40,0.787206
7,None,None,test_0,rf,pred_2_full_val,target,NaN,NaN,0.36,0.293053,0.059766,0.247273,0.36,0.787206
8,None,None,test_0,rf,pred_3_full,target,NaN,NaN,0.48,0.461014,0.254656,0.641212,0.48,0.811397
9,None,None,test_0,rf,pred_3_full_val,target,NaN,NaN,0.36,0.280000,0.067488,0.240000,0.36,0.811397
10,None,None,test_0,rf,pred_ensemble_full,target,NaN,NaN,0.44,0.417866,0.196430,0.608000,0.44,0.813088
11,None,None,test_0,rf,pred_ensemble_full_val,target,NaN,NaN,0.56,0.493244,0.384583,0.543636,0.56,0.815441

### Predictions

In [ ]:
from omicstl.simulation_utils.model_utils import predict_dl_model

# Create "new" data by shuffling existing values
new_synth_data_cont = source_synth_data_cont.iloc[:, 1:]
values = new_synth_data_cont.values.flatten()
np.random.shuffle(values)
new_synth_data_cont = pd.DataFrame(
    values.reshape(new_synth_data_cont.shape),
    columns=new_synth_data_cont.columns
)

new_synth_data_cat = source_synth_data_cat.iloc[:, 1:]
values = new_synth_data_cat.values.flatten()
np.random.shuffle(values)
new_synth_data_cat = pd.DataFrame(
    values.reshape(new_synth_data_cat.shape),
    columns=new_synth_data_cat.columns
)

# Get predicted response values on the new data
out = predict_dl_model(mult_vae_cont_model, new_synth_data_cont)
display(out)

out = predict_dl_model(mult_vae_cat_model, new_synth_data_cat)
display(out)

out = predict_dl_model(mult_mlp_cont_model, new_synth_data_cont)
display(out)

out = predict_dl_model(mult_mlp_cat_model, new_synth_data_cat)
display(out)

In [ ]:
from omicstl.simulation_utils.model_utils import predict_rf_model

out = predict_rf_model(rf_cont_model, new_synth_data_cont)
display(pd.DataFrame(out))

out = predict_rf_model(rf_cat_model, new_synth_data_cat)
display(pd.DataFrame(out))